local id = 'ECMWF/NRT_FORECAST/IFS/SCWV';
local subdir = 'ECMWF';

local ee_const = import 'earthengine_const.libsonnet';
local ee = import 'earthengine.libsonnet';
local spdx = import 'spdx.libsonnet';
local units = import 'units.libsonnet';

local license = spdx.cc_by_4_0;

local basename = std.strReplace(id, '/', '_');
local self_ee_catalog_url = ee_const.ee_catalog_url + basename;

{
  id: id,
  title: 'ECMWF Near-Realtime IFS Wave (Short-Cutoff) Forecasts',
  version: 'N/A',
  description: |||
    This dataset contains 6-day forecasts of the wave model fields generated by
    the ECMWF Integrated Forecasting System (IFS) at 0.25 degree resolution.
    We refer to these as Near-Realtime (NRT) because new products are released
    twice a day after the release of the ECMWF realtime forecast data, of which
    this is a subset. This is a "Short-Cutoff" stream, meaning the forecasts
    have a shorter range than the standard IFS WAVE forecasts. Data may be
    distributed and used commercially with
    [proper attribution](https://apps.ecmwf.int/datasets/licences/general/).

    Products are available in Earth Engine starting with the implementation of
    [Cycle 49r1](https://confluence.ecmwf.int/display/FCST/Implementation+of+IFS+Cycle+49r1)
    on 2024-11-12; earlier products are not included. For general information
    about how to use ECMWF NRT datasets, see their
    [user documentation](https://confluence.ecmwf.int/display/DAC/ECMWF+open+data%3A+real-time+forecasts+from+IFS+and+AIFS).
    Sources files are available in the
    [Google Cloud marketplace](https://console.cloud.google.com/marketplace/product/bigquery-public-data/open-data-ecmwf).
  |||,

  'gee:categories': ['climate'],
  keywords: [
    'ecmwf',
    'forecast',
    'global',
    'ocean',
  ],
  providers: [
    ee.producer_provider(
       'ECMWF', 'https://www.ecmwf.int/en/forecasts/datasets/open-data'),
    ee.host_provider(self_ee_catalog_url),
  ],
  extent: ee.extent_global('2024-11-12T18:00:00Z', null),

  summaries: {
    gsd: [28000],  // 0.25 degrees
    'eo:bands': [
      {
        name: 'mean_zero_crossing_wave_period_sfc',
        description: |||
          The mean length of time between occasions where the sea/ocean surface
          crosses mean sea level.
        |||,
        'gee:units': units.seconds,
      },
      {
        name: 'significant_height_of_combined_wind_waves_and_swell_sfc',
        description: |||
          The average height of the highest third of surface ocean/sea waves
          generated by wind and swell. It represents the vertical distance
          between the wave crest and the wave trough.
        |||,
        'gee:units': units.meter,
      },
      {
        name: 'mean_wave_direction_sfc',
        description: |||
          The mean direction of ocean/sea surface waves relative to the
          geographic location of the north pole (e.g., 0 means "coming from the
          north" and 90 "coming from the east").
        |||,
        'gee:units': units.degree,
      },
      {
        name: 'peak_wave_period_sfc',
        description: |||
          The period of the most energetic ocean waves generated by local winds
          and associated with swell. The wave period is the average time it
          takes for two consecutive wave crests, on the surface of the
          ocean/sea, to pass through a fixed point.
        |||,
        'gee:units': units.seconds,
      },
      {
        name: 'mean_wave_period_sfc',
        description: |||
          The average time it takes for two consecutive wave crests, on the
          surface of the ocean/sea, to pass through a fixed point.
        |||,
        'gee:units': units.seconds,
      },
    ],

    mean_wave_direction_sfc: {
      minimum: 0,
      maximum: 360,
      'gee:estimated_range': false,
    },
    mean_wave_period_sfc: {
      minimum: 1.0414800643920898,
      maximum: 18.36426544189453,
      'gee:estimated_range': true,
    },
    mean_zero_crossing_wave_period_sfc: {
      minimum: 0.8896015882492065,
      maximum: 17.57300567626953,
      'gee:estimated_range': true,
    },
    peak_wave_period_sfc: {
      minimum: 1.0307435989379883,
      maximum: 23.788860321044922,
      'gee:estimated_range': true,
    },
    significant_height_of_combined_wind_waves_and_swell_sfc: {
      minimum: 0.017207905650138855,
      maximum: 15.585578918457031,
      'gee:estimated_range': true,
    },

    'gee:visualizations': [
      {
        display_name: 'Significant height of combined wind waves and swell',
        lookat: {lon: 0, lat: 0, zoom: 3},
        image_visualization: {
          band_vis: {
            min: [0],
            max: [5],
            bands: ['significant_height_of_combined_wind_waves_and_swell_sfc'],
          },
        },
      },
    ],

    'gee:schema': [
      {
        name: 'creation_day',
        description: 'Day of the month when the forecast was created.',
        type: ee_const.var_type.int,
      },
      {
        name: 'creation_doy',
        description: 'Day of the year when the forecast was created.',
        type: ee_const.var_type.int,
      },
      {
        name: 'creation_hour',
        description: 'Hour of the day when the forecast was created.',
        type: ee_const.var_type.int,
      },
      {
        name: 'creation_month',
        description: 'Month of the year when the forecast was created.',
        type: ee_const.var_type.int,
      },
      {
        name: 'creation_time',
        description: |||
          Time, in unix epoch milliseconds, when forecast was created.
        |||,
        type: ee_const.var_type.int,
      },
      {
        name: 'creation_year',
        description: 'Year when the forecast was created.',
        type: ee_const.var_type.int,
      },
      {
        name: 'forecast_hours',
        description: |||
          Hours into the future, relative to `creation_time`, of the forecast.
        |||,
        type: ee_const.var_type.int,
      },
      {
        name: 'forecast_time',
        description: 'Time, in unix epoch milliseconds, of the forecast.',
        type: ee_const.var_type.int,
      },
      {
        name: 'model',
        description: |||
          The ECMWF forecasting model:

          * ifs: Integrated Forecasting System
          * aifs: Artificial Intelligence/Integrated Forecasting System
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'stream',
        description: |||
          The stream from which the variables were fetched. See the full list
          [here](https://codes.ecmwf.int/grib/format/mars/stream/).
        |||,
        type: ee_const.var_type.string,
      },
    ],
  },

  'gee:interval': {
    type: 'cadence',
    unit: 'hour',
    interval: 12,
  },

  'sci:doi': '10.21957/open-data',
  'gee:terms_of_use': ee.gee_terms_of_use(license),
  'gee:type': ee_const.gee_type.image_collection,
  license: license.id,
  links: ee.standardLinks(subdir, id),
  type: ee_const.stac_type.collection,
  stac_version: ee_const.stac_version,
  stac_extensions: [
    ee_const.ext_eo,
    ee_const.ext_sci,
    ee_const.ext_ver,
  ],
}