local id = 'ECMWF/NRT_FORECAST/IFS/OPER';
local subdir = 'ECMWF';

local ee_const = import 'earthengine_const.libsonnet';
local ee = import 'earthengine.libsonnet';
local spdx = import 'spdx.libsonnet';
local units = import 'units.libsonnet';

local license = spdx.cc_by_4_0;

local basename = std.strReplace(id, '/', '_');
local self_ee_catalog_url = ee_const.ee_catalog_url + basename;

local pressure_levels = [
  100, 1000, 150, 200, 250, 300, 400, 50, 500, 600, 700, 850, 925,
];

{
  id: id,
  title: 'ECMWF Near-Realtime IFS Atmospheric Forecasts',
  version: 'N/A',
  description: |||
    This dataset contains 15-day forecasts of the atmospheric model variables
    generated by the ECMWF Integrated Forecasting System (IFS) at 0.25 degree
    resolution. We refer to these as Near-Realtime (NRT) because new products
    are released twice a day after the release of the ECMWF realtime forecast
    data, of which this is a subset. Data may be distributed and used
    commercially with
    [proper attribution](https://apps.ecmwf.int/datasets/licences/general/).

    Products are available in Earth Engine starting with the implementation of
    [Cycle 49r1](https://confluence.ecmwf.int/display/FCST/Implementation+of+IFS+Cycle+49r1)
    on 2024/11/12; earlier products are not included. For general information
    about how to use ECMWF NRT datasets, see their
    [user documentation](https://confluence.ecmwf.int/display/DAC/ECMWF+open+data%3A+real-time+forecasts+from+IFS+and+AIFS).
    Sources files are available in the
    [Google Cloud marketplace](https://console.cloud.google.com/marketplace/product/bigquery-public-data/open-data-ecmwf).
  |||,

  'gee:categories': ['climate'],
  keywords: [
    'dewpoint',
    'ecmwf',
    'forecast',
    'global',
    'humidity',
    'precipitation',
    'pressure',
    'radiation',
    'rainfall',
    'snow',
    'soil_moisture',
    'soil_temperature',
    'temperature',
    'wind',
  ],
  providers: [
    ee.producer_provider(
       'ECMWF', 'https://www.ecmwf.int/en/forecasts/datasets/open-data'),
    ee.host_provider(self_ee_catalog_url),
  ],
  extent: ee.extent_global('2024-11-12T12:00:00Z', null),

  summaries: {
    gsd: [28000],  // 0.25 degrees
    'eo:bands': [
      {
        name: 'u_component_of_wind_100m_sfc',
        description: |||
          The horizontal speed of air moving towards the east, at a height of
          100 meters above the surface of the Earth.
        |||,
        'gee:units': units.velocity_si,
      },
      {
        name: 'v_component_of_wind_100m_sfc',
        description: |||
          The horizontal speed of air moving towards the north, at a height of
          100 meters above the surface of the Earth.
        |||,
        'gee:units': units.velocity_si,
      },
      {
        name: 'u_component_of_wind_10m_sfc',
        description: |||
          The horizontal speed of air moving towards the east, at a height of
          10 meters above the surface of the Earth.
        |||,
        'gee:units': units.velocity_si,
      },
      {
        name: 'v_component_of_wind_10m_sfc',
        description: |||
          The horizontal speed of air moving towards the north, at a height of
          10 meters above the surface of the Earth.
        |||,
        'gee:units': units.velocity_si,
      },
      {
        name: 'dewpoint_temperature_2m_sfc',
        description: |||
          The temperature to which the air, at 2 meters above the surface of
          the Earth, would have to be cooled for saturation to occur.
        |||,
        'gee:units': units.celsius,
      },
      {
        name: 'temperature_2m_sfc',
        description: |||
          The temperature of air at 2m above the surface of land, sea or in-land
          waters.
        |||,
        'gee:units': units.celsius,
      },
      {
        name: 'snow_albedo_sfc',
        description: |||
          The fraction of solar (shortwave) radiation reflected by snow across
          the solar spectrum.
        |||,
        'gee:units': units.dimensionless,
      },
      {
        name: 'eastward_turbulent_surface_stress_sfc',
        description: |||
          The accumulated stress on the Earth's surface in the eastward
          direction due to both the turbulent interactions between the
          atmosphere and the surface, and to turbulent orographic form drag.
        |||,
        'gee:units': units.pascal_seconds,
      },
    ] + [
      {
        name: 'divergence_pl' + pl,
        description: |||
          The rate at which air is spreading out horizontally from a point, per
          square meter, measured at a pressure level of
        ||| + pl + |||
          &nbsp;hPa. This parameter is positive for air that is spreading out,
          or diverging, and negative for the opposite, for air that is
          concentrating, or converging.
        |||,
        'gee:units': units.pascal_seconds,
      } for pl in pressure_levels
    ] + [
      {
        name: 'geopotential_height_pl' + pl,
        description: |||
          A measure of the height of a point in the atmosphere in relation to
          its potential energy, at a pressure level of
        ||| + pl + |||
          &nbsp;hPa. It is calculated by dividing the geopotential by the
          Earth's mean gravitational acceleration, g.
        |||,
        'gee:units': units.geopotential_meter,
      } for pl in pressure_levels
    ] + [
      {
        name: 'land_sea_mask_sfc',
        description: |||
          The proportion of land, as opposed to ocean or inland waters (lakes,
          reservoirs, rivers and coastal waters).
        |||,
        'gee:units': units.dimensionless,
      },
      {
        name: 'mean_sea_level_pressure_sfc',
        description: |||
          A measure of the weight that all the air in a column vertically above
          the area of Earth's surface would have at that point, if the point
          were located at the mean sea level, calculated over all surfaces.
        |||,
        'gee:units': units.pascal,
      },
      {
        name: 'most_unstable_convective_available_potential_energy_sfc',
        description: |||
          The parcel with the most Convective Available Potential Energy (CAPE,
          the amount of energy available for convection) found in the atmosphere
          from the surface up to 350 hPa.
        |||,
        'gee:units': units.joules_per_kg,
      },
      {
        name: 'northward_turbulent_surface_stress_sfc',
        description: |||
          The accumulated stress on the Earth's surface in the northward
          direction due to both the turbulent interactions between the
          atmosphere and the surface, and to turbulent orographic form drag.
        |||,
        'gee:units': units.pascal_seconds,
      },
      {
        name: 'precipitation_type_sfc',
        description: |||
          The type of precipitation at the surface:

          * 0 = No precipitation
          * 1 = Rain
          * 3 = Freezing rain (i.e. supercooled raindrops which freeze on
          contact with the ground and other surfaces)
          * 5 = Snow
          * 6 = Wet snow (i.e. snow particles which are starting to melt)
          * 7 = Mixture of rain and snow
          * 8 = Ice pellets
          * 12 = Freezing drizzle (i.e. supercooled drizzle which freezes on
          contact with the ground and other surfaces)
        |||,
      },
    ] + [
      {
        name: 'specific_humidity_pl' + pl,
        description: |||
          The mass of water vapour per kilogram of moist air (the sum of the dry
          air, water vapour, cloud liquid, cloud ice, rain and falling snow) at
          a pressure level of
        ||| + pl + ' hPa.',
        'gee:units': units.mass_fraction,
      } for pl in pressure_levels
    ] + [
      {
        name: 'relative_humidity_pl' + pl,
        description: |||
          The water vapour pressure as a percentage of the value at which the
          air becomes saturated (the point at which water vapour begins to
          condense into liquid water or deposition into ice) at a pressure level
          of
        ||| + pl + ' hPa.',
        'gee:units': units.percent,
      } for pl in pressure_levels
    ] + [
      {
        name: 'runoff_sfc',
        description: |||
          A cumulative measurement (since forecast hour 0) of the amount of
          water not absorbed by the soil from rainfall, snow melt, etc. It is
          the depth the water would have if it were spread evenly over the grid
          box.
        |||,
        'gee:units': units.meter,
      },
      {
        name: 'sea_ice_thickness_sfc',
        description: 'Sea ice thickness.',
        'gee:units': units.meter,
      },
      {
        name: 'skin_temperature_sfc',
        description: |||
          The temperature of the surface of the Earth. It represents the
          temperature of the uppermost surface layer, which has no heat capacity
          and so can respond instantaneously to changes in surface fluxes.
        |||,
        'gee:units': units.celsius,
      },
      {
        name: 'soil_temperature_sol1',
        description: |||
          The temperature of the soil at the middle of layer 1, 0-7 cm below
          the surface.
        |||,
        'gee:units': units.kelvin,
      },
      {
        name: 'soil_temperature_sol2',
        description: |||
          The temperature of the soil at the middle of layer 2, 7-28 cm below
          the surface.
        |||,
        'gee:units': units.kelvin,
      },
      {
        name: 'soil_temperature_sol3',
        description: |||
          The temperature of the soil at the middle of layer 3, 28-100 cm below
          the surface.
        |||,
        'gee:units': units.kelvin,
      },
      {
        name: 'soil_temperature_sol4',
        description: |||
          The temperature of the soil at the middle of layer 4, 100-289 cm below
          the surface.
        |||,
        'gee:units': units.kelvin,
      },
      {
        name: 'surface_pressure_sfc',
        description: |||
          The pressure (force per unit area) of the atmosphere on the surface of
          land, sea and in-land water. It is a measure of the weight of all the
          air in a column vertically above the area of the Earth's surface
          represented at a fixed point.
        |||,
        'gee:units': units.pascal,
      },
      {
        name: 'surface_net_solar_radiation_sfc',
        description: |||
          A cumulative measurement (since forecast hour 0) of the amount of
          solar radiation that reaches a horizontal plane at the surface of the
          Earth (both direct and diffuse) minus the amount reflected by the
          Earth's surface.
        |||,
        'gee:units': units.joules_per_meter2,
      },
      {
        name: 'surface_solar_radiation_downwards_sfc',
        description: |||
          A cumulative measurement (since forecast hour 0) of the amount of
          solar radiation that reaches a horizontal plane at the surface of the
          Earth (both direct and diffuse).
        |||,
        'gee:units': units.joules_per_meter2,
      },
      {
        name: 'surface_net_thermal_radiation_sfc',
        description: |||
          A cumulative measurement (since forecast hour 0) of the difference
          between the download and upward thermal radiation at the surface of
          the Earth, where thermal radiation refers to radiation emitted by the
          atmosphere, clouds and the surface.
        |||,
        'gee:units': units.joules_per_meter2,
      },
      {
        name: 'surface_thermal_radiation_downwards_sfc',
        description: |||
          A cumulative measurement (since forecast hour 0) of the amount of
          thermal radiation emitted by the atmosphere and clouds that reaches a
          horizontal plane at the surface of the Earth.
        |||,
        'gee:units': units.joules_per_meter2,
      },
      {
        name: 'eastward_surface_sea_water_velocity_sfc',
        description: 'The velocity of sea water moving east.',
        'gee:units': units.velocity_si,
      },
      {
        name: 'northward_surface_sea_water_velocity_sfc',
        description: 'The velocity of sea water moving north.',
       'gee:units': units.velocity_si,
      },
    ] + [
      {
        name: 'temperature_pl' + pl,
        description: |||
          The temperature of the atmoshere at a pressure level of
        ||| + pl + ' hPa.',
        'gee:units': units.celsius,
      } for pl in pressure_levels
    ] + [
      {
        name: 'total_column_water_sfc',
        description: |||
          The sum of water vapour, liquid water, cloud ice, rain and snow in a
          column extending from the surface of the Earth to the top of the
          atmosphere.
        |||,
        'gee:units': units.area_density,
      },
      {
        name: 'total_column_water_vapour_sfc',
        description: |||
          The total amount of water vapour in a column extending from the
          surface of the Earth to the top of the atmosphere.
        |||,
        'gee:units': units.area_density,
      },
      {
        name: 'total_precipitation_sfc',
        description: |||
          Cumulative measurement (since forecast hour 0) of the amount of liquid
          and frozen water, comprising rain and snow, that falls to the Earth's
          surface. It is the depth the water would have if it were spread evenly
          over the grid box.
        |||,
        'gee:units': units.meter,
      },
      {
        name: 'total_precipitation_rate_sfc',
        description: |||
          The mean rate of total precipitation as the water equivalent in
          meters (the depth it would have if it were spread evenly over the
          grid box) which falls per second.
        |||,
        // Not really velocity, but m/s as a rate.
        'gee:units': units.velocity_si,
      },
      {
        name: 'top_net_thermal_radiation_sfc',
        description: |||
          Cumulative measurement (since forecast hour 0) of negative Outgoing
          Longwave Radiation (OLR), the thermal radiation emitted to space at
          the top of the atmosphere.
        |||,
        'gee:units': units.joules_per_meter2,
      },
    ] + [
      {
        name: 'u_component_of_wind_pl' + pl,
        description: |||
          The horizontal speed of air moving towards the east at a pressure
          level of
        ||| + pl + ' hPa.',
        'gee:units': units.velocity_si,
      } for pl in pressure_levels
    ] + [
      {
        name: 'v_component_of_wind_pl' + pl,
        description: |||
          The horizontal speed of air moving towards the north at a pressure
          level of
        ||| + pl + ' hPa.',
        'gee:units': units.velocity_si,
      } for pl in pressure_levels
    ] + [
      {
        name: 'vorticity_pl' + pl,
        description: |||
          The rotation of air in the horizontal, around a vertical axis,
          relative to a fixed point on the surface of the Earth at a pressure
          level of
        ||| + pl + ' hPa.',
        'gee:units': units.inverse_second,
      } for pl in pressure_levels
    ] + [
      {
        name: 'volumetric_soil_moisture_sol1',
        description: |||
          The volume of water in soil layer 1, 0-7 cm below the surface.
        |||,
        'gee:units': units.volume_fraction,
      },
      {
        name: 'volumetric_soil_moisture_sol2',
        description: |||
          The volume of water in soil layer 2, 7-28 cm below the surface.
        |||,
        'gee:units': units.volume_fraction,
      },
      {
        name: 'volumetric_soil_moisture_sol3',
        description: |||
          The volume of water in soil layer 3, 28-100 cm below the surface.
        |||,
        'gee:units': units.volume_fraction,
      },
      {
        name: 'volumetric_soil_moisture_sol4',
        description: |||
          The volume of water in soil layer 4, 100-289 cm below the surface.
        |||,
        'gee:units': units.volume_fraction,
      },
    ] + [
      {
        name: 'vertical_velocity_pl' + pl,
        description: |||
          The speed of air motion in the upward or downward direction, at a
          pressure level of
        ||| + pl + ' hPa.',
        'gee:units': units.pascal_seconds,
      } for pl in pressure_levels
    ] + [
      {
        name: 'sea_surface_height_sfc',
        description: 'Sea surface height.',
        'gee:units': units.meter,
      },
      {
        name: 'max_10m_wind_gust_since_last_post_processing_sfc',
        description: |||
          Maximum 3 second wind at 10 m height as defined by World
          Meteorological Organization. Available at forecast hours 0-90 and
          150-360.
        |||,
        'gee:units': units.velocity_si,
      },
      {
        name: 'max_10m_wind_gust_last_3h_sfc',
        description: |||
          The maximum wind gust in the last 3 hours at a height of ten meters
          above the surface of the Earth. Available at forecast hours 93-144.
        |||,
        'gee:units': units.velocity_si,
      },
      {
        name: 'min_2m_temperature_last_3h_sfc',
        description: |||
          The lowest value of 2 meter temperature in the previous 3 hour period.
          Available at forecast hours 0-144.
        |||,
        'gee:units': units.celsius,
      },
      {
        name: 'min_2m_temperature_last_6h_sfc',
        description: |||
          The lowest value of 2 meter temperature in the previous 6 hour period.
          Available at forecast hours 150-360.
        |||,
        'gee:units': units.celsius,
      },
      {
        name: 'max_2m_temperature_last_3h_sfc',
        description: |||
          The highest value of 2 meter temperature in the previous 3 hour
          period. Available at forecast hours 0-144.
        |||,
        'gee:units': units.celsius,
      },
      {
        name: 'max_2m_temperature_last_6h_sfc',
        description: |||
          The highest value of 2 meter temperature in the previous 6 hour
          period. Available at forecast hours 150-360.
        |||,
        'gee:units': units.celsius,
      },
    ],

    u_component_of_wind_100m_sfc: {
      minimum: -53.36,
      maximum: 53.26,
      'gee:estimated_range': true,
    },
    v_component_of_wind_100m_sfc: {
      minimum: -49.45,
      maximum: 63.75,
      'gee:estimated_range': true,
    },
    u_component_of_wind_10m_sfc: {
      minimum: -46.87,
      maximum: 46.25,
      'gee:estimated_range': true,
    },
    v_component_of_wind_10m_sfc: {
      minimum: -43.74,
      maximum: 57.40,
      'gee:estimated_range': true,
    },
    dewpoint_temperature_2m_sfc: {
      minimum: -79.58,
      maximum: 30.25,
      'gee:estimated_range': true,
    },
    temperature_2m_sfc: {
      minimum: -79.58,
      maximum: 46.33,
      'gee:estimated_range': true,
    },
    snow_albedo_sfc: {
      minimum: 0.50,
      maximum: 0.85,
      'gee:estimated_range': true,
    },
    eastward_turbulent_surface_stress_sfc: {
      minimum: -12311551,
      maximum: 14940493,
      'gee:estimated_range': true,
    },
    divergence_pl100: {
      minimum: -0.0012,
      maximum: 0.0020,
      'gee:estimated_range': true,
    },
    divergence_pl1000: {
      minimum: -0.0018,
      maximum: 0.0001,
      'gee:estimated_range': true,
    },
    divergence_pl150: {
      minimum: -0.0010,
      maximum: 0.0016,
      'gee:estimated_range': true,
    },
    divergence_pl200: {
      minimum: -0.0010,
      maximum: 0.0012,
      'gee:estimated_range': true,
    },
    divergence_pl250: {
      minimum: -0.0010,
      maximum: 0.0011,
      'gee:estimated_range': true,
    },
    divergence_pl300: {
      minimum: -0.0014,
      maximum: 0.0011,
      'gee:estimated_range': true,
    },
    divergence_pl400: {
      minimum: -0.0010,
      maximum: 0.0010,
      'gee:estimated_range': true,
    },
    divergence_pl50: {
      minimum: -0.0013,
      maximum: 0.0010,
      'gee:estimated_range': true,
    },
    divergence_pl500: {
      minimum: -0.0010,
      maximum: 0.0010,
      'gee:estimated_range': true,
    },
    divergence_pl600: {
      minimum: -0.0011,
      maximum: 0.0010,
      'gee:estimated_range': true,
    },
    divergence_pl700: {
      minimum: -0.0012,
      maximum: 0.0009,
      'gee:estimated_range': true,
    },
    divergence_pl850: {
      minimum: -0.0011,
      maximum: 0.0010,
      'gee:estimated_range': true,
    },
    divergence_pl925: {
      minimum: -0.0016,
      maximum: 0.0011,
      'gee:estimated_range': true,
    },
    geopotential_height_pl100: {
      minimum: 14693.90,
      maximum: 16815.55,
      'gee:estimated_range': true,
    },
    geopotential_height_pl1000: {
      minimum: -647.25,
      maximum: 452.31,
      'gee:estimated_range': true,
    },
    geopotential_height_pl150: {
      minimum: 12279.07,
      maximum: 14446.04,
      'gee:estimated_range': true,
    },
    geopotential_height_pl200: {
      minimum: 10524.51,
      maximum: 12608.83,
      'gee:estimated_range': true,
    },
    geopotential_height_pl250: {
      minimum: 9148.03,
      maximum: 11099.75,
      'gee:estimated_range': true,
    },
    geopotential_height_pl300: {
      minimum: 7999.95,
      maximum: 9810.31,
      'gee:estimated_range': true,
    },
    geopotential_height_pl400: {
      minimum: 6111.43,
      maximum: 7694.22,
      'gee:estimated_range': true,
    },
    geopotential_height_pl50: {
      minimum: 18601.52,
      maximum: 20939.84,
      'gee:estimated_range': true,
    },
    geopotential_height_pl500: {
      minimum: 4627.77,
      maximum: 5974.44,
      'gee:estimated_range': true,
    },
    geopotential_height_pl600: {
      minimum: 3384.05,
      maximum: 4526.21,
      'gee:estimated_range': true,
    },
    geopotential_height_pl700: {
      minimum: 2251.74,
      maximum: 3281.08,
      'gee:estimated_range': true,
    },
    geopotential_height_pl850: {
      minimum: 742.93,
      maximum: 1711.14,
      'gee:estimated_range': true,
    },
    geopotential_height_pl925: {
      minimum: 32.27,
      maximum: 1057.44,
      'gee:estimated_range': true,
    },
    land_sea_mask_sfc: {
      minimum: 0,
      maximum: 1,
      'gee:estimated_range': false,
    },
    mean_sea_level_pressure_sfc: {
      minimum: 92686.50,
      maximum: 106341.13,
      'gee:estimated_range': true,
    },
    most_unstable_convective_available_potential_energy_sfc: {
      minimum: 0,
      maximum: 9833.5,
      'gee:estimated_range': true,
    },
    northward_turbulent_surface_stress_sfc: {
      minimum: -6431634,
      maximum: 8478005,
      'gee:estimated_range': true,
    },
    precipitation_type_sfc: {
      minimum: 0,
      maximum: 12,
      'gee:estimated_range': false,
    },
    specific_humidity_pl100: {
      minimum: 0,
      maximum: 0.000025,
      'gee:estimated_range': true,
    },
    specific_humidity_pl1000: {
      minimum: 0,
      maximum: 0.027,
      'gee:estimated_range': true,
    },
    specific_humidity_pl150: {
      minimum: 0,
      maximum: 0.00017,
      'gee:estimated_range': true,
    },
    specific_humidity_pl200: {
      minimum: 0,
      maximum: 0.00089,
      'gee:estimated_range': true,
    },
    specific_humidity_pl250: {
      minimum: 0,
      maximum: 0.0024,
      'gee:estimated_range': true,
    },
    specific_humidity_pl300: {
      minimum: 0,
      maximum: 0.0044,
      'gee:estimated_range': true,
    },    
    specific_humidity_pl400: {
      minimum: 0,
      maximum: 0.0064,
      'gee:estimated_range': true,
    },
    specific_humidity_pl50: {
      minimum: 0,
      maximum: 0.0000073,
      'gee:estimated_range': true,
    },
    specific_humidity_pl500: {
      minimum: 0,
      maximum: 0.0097,
      'gee:estimated_range': true,
    },
    specific_humidity_pl600: {
      minimum: 0,
      maximum: 0.012,
      'gee:estimated_range': true,
    },
    specific_humidity_pl700: {
      minimum: 0,
      maximum: 0.015,
      'gee:estimated_range': true,
    },
    specific_humidity_pl850: {
      minimum: 0,
      maximum: 0.019,
      'gee:estimated_range': true,
    },
    specific_humidity_pl925: {
      minimum: 0,
      maximum: 0.024,
      'gee:estimated_range': true,
    },
    relative_humidity_pl100: {
      minimum: -6.15,
      maximum: 137.32,
      'gee:estimated_range': true,
    },
    relative_humidity_pl1000: {
      minimum: -8.75,
      maximum: 131.46,
      'gee:estimated_range': true,
    },
    relative_humidity_pl150: {
      minimum: -5.93,
      maximum: 160.47,
      'gee:estimated_range': true,
    },
    relative_humidity_pl200: {
      minimum: -6.54,
      maximum: 145.93,
      'gee:estimated_range': true,
    },
    relative_humidity_pl250: {
      minimum: -7.08,
      maximum: 143.48,
      'gee:estimated_range': true,
    },    
    relative_humidity_pl300: {
      minimum: -8.08,
      maximum: 136.92,
      'gee:estimated_range': true,
    },
    relative_humidity_pl400: {
      minimum: -12.31,
      maximum: 136.92,
      'gee:estimated_range': true,
    },
    relative_humidity_pl50: {
      minimum: 0.021,
      maximum: 140.17,
      'gee:estimated_range': true,
    },
    relative_humidity_pl500: {
      minimum: -10.16,
      maximum: 126.13,
      'gee:estimated_range': true,
    },
    relative_humidity_pl600: {
      minimum: -8.73,
      maximum: 132.07,
      'gee:estimated_range': true,
    },
    relative_humidity_pl700: {
      minimum: -8.60,
      maximum: 131.50,
      'gee:estimated_range': true,
    },
    relative_humidity_pl850: {
      minimum: -7.04,
      maximum: 131.48,
      'gee:estimated_range': true,
    },
    relative_humidity_pl925: {
      minimum: -9.61,
      maximum: 132.04,
      'gee:estimated_range': true,
    },
    runoff_sfc: {
      minimum: 0,
      maximum: 1.85,
      'gee:estimated_range': true,
    },
    sea_ice_thickness_sfc: {
      minimum: 0,
      maximum: 9999,
      'gee:estimated_range': true,
    },
    skin_temperature_sfc: {
      minimum: -82.08,
      maximum: 69.60,
      'gee:estimated_range': true,
    },
    soil_temperature_sol1: {
      minimum: 214.05,
      maximum: 330.78,
      'gee:estimated_range': true,
    },
    soil_temperature_sol2: {
      minimum: 214.06,
      maximum: 318.86,
      'gee:estimated_range': true,
    },
    soil_temperature_sol3: {
      minimum: 214.10,
      maximum: 314.26,
      'gee:estimated_range': true,
    },
    soil_temperature_sol4: {
      minimum: 214.17,
      maximum: 314.41,
      'gee:estimated_range': true,
    },
    surface_pressure_sfc: {
      minimum: 47323.99,
      maximum: 107444.59,
      'gee:estimated_range': true,
    },
    surface_net_solar_radiation_sfc: {
      minimum: 0,
      maximum: 492011520,
      'gee:estimated_range': true,
    },
    surface_solar_radiation_downwards_sfc: {
      minimum: 0,
      maximum: 611336192,
      'gee:estimated_range': true,
    },
    surface_net_thermal_radiation_sfc: {
      minimum: -287437568,
      maximum: 14857416,
      'gee:estimated_range': true,
    },
    surface_thermal_radiation_downwards_sfc: {
      minimum: 0,
      maximum: 589142976,
      'gee:estimated_range': true,
    },
    eastward_surface_sea_water_velocity_sfc: {
      minimum: -3.77,
      maximum: 2.03,
      'gee:estimated_range': true,
    },
    northward_surface_sea_water_velocity_sfc: {
      minimum: -2.74,
      maximum: 1.82,
      'gee:estimated_range': true,
    },
    temperature_pl100: {
      minimum: -90.11,
      maximum: -31.75,
      'gee:estimated_range': true,
    },
    temperature_pl1000: {
      minimum: -52.05,
      maximum: 46.79,
      'gee:estimated_range': true,
    },
    temperature_pl150: {
      minimum: -85.44,
      maximum: -34.15,
      'gee:estimated_range': true,
    },
    temperature_pl200: {
      minimum: -79.16,
      maximum: -32.29,
      'gee:estimated_range': true,
    },
    temperature_pl250: {
      minimum: -74.30,
      maximum: -23.39,
      'gee:estimated_range': true,
    },
    temperature_pl300: {
      minimum: -68.69,
      maximum: -13.95,
      'gee:estimated_range': true,
    },
    temperature_pl400: {
      minimum: -60.07,
      maximum: -2.25,
      'gee:estimated_range': true,
    },    
    temperature_pl50: {
      minimum: -91.63,
      maximum: -18.46,
      'gee:estimated_range': true,
    },
    temperature_pl500: {
      minimum: -53.27,
      maximum: 8.57,
      'gee:estimated_range': true,
    },
    temperature_pl600: {
      minimum: -70.11,
      maximum: 18.69,
      'gee:estimated_range': true,
    },
    temperature_pl700: {
      minimum: -69.81,
      maximum: 24.50,
      'gee:estimated_range': true,
    },
    temperature_pl850: {
      minimum: -54.99,
      maximum: -35.58,
      'gee:estimated_range': true,
    },
    temperature_pl925: {
      minimum: -52.38,
      maximum: 42.02,
      'gee:estimated_range': true,
    },
    total_column_water_sfc: {
      minimum: 0.05,
      maximum: 127.04,
      'gee:estimated_range': true,
    },
    total_column_water_vapour_sfc: {
      minimum: 0.05,
      maximum: 83.54,
      'gee:estimated_range': true,
    },
    total_precipitation_sfc: {
      minimum: 0,
      maximum: 1.86,
      'gee:estimated_range': true,
    },
    total_precipitation_rate_sfc: {
      minimum: 0,
      maximum: 0.023,
      'gee:estimated_range': true,
    },
    top_net_thermal_radiation_sfc: {
      minimum: -425198592,
      maximum: 0,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl100: {
      minimum: -47.11,
      maximum: 86.87,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl1000: {
      minimum: -38.74,
      maximum: 39.05,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl150: {
      minimum: -50.50,
      maximum: 102.75,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl200: {
      minimum: -58.21,
      maximum: 120.00,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl250: {
      minimum: -58.35,
      maximum: 120.48,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl300: {
      minimum: -58.68,
      maximum: 119.08,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl400: {
      minimum: -57.09,
      maximum: 96.34,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl50: {
      minimum: -62.03,
      maximum: 77.22,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl500: {
      minimum: -58.43,
      maximum: 83.02,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl600: {
      minimum: -57.80,
      maximum: 65.01,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl700: {
      minimum: -57.72,
      maximum: 56.19,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl850: {
      minimum: -60.52,
      maximum: 57.48,
      'gee:estimated_range': true,
    },
    u_component_of_wind_pl925: {
      minimum: -56.88,
      maximum: 55.04,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl100: {
      minimum: -57.62,
      maximum: 49.17,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl1000: {
      minimum: -40.45,
      maximum: 43.98,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl150: {
      minimum: -61.40,
      maximum: 64.33,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl200: {
      minimum: -76.17,
      maximum: 82.86,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl250: {
      minimum: -86.18,
      maximum: 94.55,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl300: {
      minimum: -87.37,
      maximum: 91.05,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl400: {
      minimum: -73.27,
      maximum: 83.39,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl50: {
      minimum: -74.60,
      maximum: 71.44,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl500: {
      minimum: -62.97,
      maximum: 71.87,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl600: {
      minimum: -52.43,
      maximum: 63.38,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl700: {
      minimum: -57.63,
      maximum: 57.62,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl850: {
      minimum: -60.95,
      maximum: 62.67,
      'gee:estimated_range': true,
    },
    v_component_of_wind_pl925: {
      minimum: -59.31,
      maximum: 59.90,
      'gee:estimated_range': true,
    },
    vorticity_pl100: {
      minimum: -0.0010,
      maximum: 0.0012,
      'gee:estimated_range': true,
    },
    vorticity_pl1000: {
      minimum: -0.0033,
      maximum: 0.0020,
      'gee:estimated_range': true,
    },
    vorticity_pl150: {
      minimum: -0.0012,
      maximum: 0.0012,
      'gee:estimated_range': true,
    },
    vorticity_pl200: {
      minimum: -0.0018,
      maximum: 0.0009,
      'gee:estimated_range': true,
    },
    vorticity_pl250: {
      minimum: -0.0021,
      maximum: 0.0012,
      'gee:estimated_range': true,
    },
    vorticity_pl300: {
      minimum: -0.0026,
      maximum: 0.0017,
      'gee:estimated_range': true,
    },
    vorticity_pl400: {
      minimum: -0.0031,
      maximum: 0.0019,
      'gee:estimated_range': true,
    },
    vorticity_pl50: {
      minimum: -0.0010,
      maximum: 0.0011,
      'gee:estimated_range': true,
    },
    vorticity_pl500: {
      minimum: -0.0033,
      maximum: 0.0022,
      'gee:estimated_range': true,
    },
    vorticity_pl600: {
      minimum: -0.0033,
      maximum: 0.0022,
      'gee:estimated_range': true,
    },
    vorticity_pl700: {
      minimum: -0.0038,
      maximum: 0.0022,
      'gee:estimated_range': true,
    },
    vorticity_pl850: {
      minimum: -0.0039,
      maximum: 0.0023,
      'gee:estimated_range': true,
    },
    vorticity_pl925: {
      minimum: -0.0045,
      maximum: 0.0025,
      'gee:estimated_range': true,
    },
    volumetric_soil_moisture_sol1: {
      minimum: 0,
      maximum: 0.77,
      'gee:estimated_range': true,
    },
    volumetric_soil_moisture_sol2: {
      minimum: 0,
      maximum: 0.77,
      'gee:estimated_range': true,
    },
    volumetric_soil_moisture_sol3: {
      minimum: 0,
      maximum: 0.77,
      'gee:estimated_range': true,
    },
    volumetric_soil_moisture_sol4: {
      minimum: 0,
      maximum: 0.77,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl100: {
      minimum: -5.59,
      maximum: 3.23,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl1000: {
      minimum: -5.17,
      maximum: 11.18,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl150: {
      minimum: -13.48,
      maximum: 4.36,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl200: {
      minimum: -17.38,
      maximum: 5.35,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl250: {
      minimum: -19.85,
      maximum: 5.28,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl300: {
      minimum: -21.45,
      maximum: 6.63,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl400: {
      minimum: -21.25,
      maximum: 14.18,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl50: {
      minimum: -2.38,
      maximum: 1.92,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl500: {
      minimum: -23.23,
      maximum: 15.84,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl600: {
      minimum: -27.57,
      maximum: 15.58,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl700: {
      minimum: -27.71,
      maximum: 14.34,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl850: {
      minimum: -20.67,
      maximum: 15.34,
      'gee:estimated_range': true,
    },
    vertical_velocity_pl925: {
      minimum: -12.33,
      maximum: 12.63,
      'gee:estimated_range': true,
    },
    sea_surface_height_sfc: {
      minimum: -2.12,
      maximum: 9999,
      'gee:estimated_range': true,
    },
    max_10m_wind_gust_since_last_post_processing_sfc: {
      minimum: 0,
      maximum: 72.95,
      'gee:estimated_range': true,
    },
    max_10m_wind_gust_last_3h_sfc: {
      minimum: 0,
      maximum: 76.40,
      'gee:estimated_range': true,
    },
    min_2m_temperature_last_3h_sfc: {
      minimum: -273.15,
      maximum: 44.05,
      'gee:estimated_range': true,
    },
    min_2m_temperature_last_6h_sfc: {
      minimum: -79.94,
      maximum: 44.01,
      'gee:estimated_range': true,
    },
    max_2m_temperature_last_3h_sfc: {
      minimum: -273.15,
      maximum: 47.31,
      'gee:estimated_range': true,
    },
    max_2m_temperature_last_6h_sfc: {
      minimum: -77.58,
      maximum: 50.39,
      'gee:estimated_range': true,
    },

    'gee:visualizations': [
      {
        display_name: 'Temperature 2m above the surface (Celsius)',
        lookat: {lon: 125, lat: 31, zoom: 4},
        image_visualization: {
          band_vis: {
            min: [-20],
            max: [40],
            palette: ['purple', 'blue', 'green', 'yellow', 'orange', 'red'],
            bands: ['temperature_2m_sfc'],
          },
        },
      },
    ],

    'gee:schema': [
      {
        name: 'creation_day',
        description: 'Day of the month when the forecast was created.',
        type: ee_const.var_type.int,
      },
      {
        name: 'creation_doy',
        description: 'Day of the year when the forecast was created.',
        type: ee_const.var_type.int,
      },
      {
        name: 'creation_hour',
        description: 'Hour of the day when the forecast was created.',
        type: ee_const.var_type.int,
      },
      {
        name: 'creation_month',
        description: 'Month of the year when the forecast was created.',
        type: ee_const.var_type.int,
      },
      {
        name: 'creation_time',
        description: |||
          Time, in unix epoch milliseconds, when forecast was created.
        |||,
        type: ee_const.var_type.int,
      },
      {
        name: 'creation_year',
        description: 'Year when the forecast was created.',
        type: ee_const.var_type.int,
      },
      {
        name: 'forecast_hours',
        description: |||
          Hours into the future, relative to `creation_time`, of the forecast.
        |||,
        type: ee_const.var_type.int,
      },
      {
        name: 'forecast_time',
        description: 'Time, in unix epoch milliseconds, of the forecast.',
        type: ee_const.var_type.int,
      },
      {
        name: 'model',
        description: |||
          The ECMWF forecasting model:

          * ifs: Integrated Forecasting System
          * aifs: Artificial Intelligence/Integrated Forecasting System
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'stream',
        description: |||
          The stream from which the variables were fetched. See the full list
          [here](https://codes.ecmwf.int/grib/format/mars/stream/).
        |||,
        type: ee_const.var_type.string,
      },
    ],
  },

  'gee:interval': {
    type: 'cadence',
    unit: 'hour',
    interval: 12,
  },

  'sci:doi': '10.21957/open-data',
  'gee:terms_of_use': ee.gee_terms_of_use(license),
  'gee:type': ee_const.gee_type.image_collection,
  license: license.id,
  links: ee.standardLinks(subdir, id),
  type: ee_const.stac_type.collection,
  stac_version: ee_const.stac_version,
  stac_extensions: [
    ee_const.ext_eo,
    ee_const.ext_sci,
    ee_const.ext_ver,
  ],
}
