local id = 'USDA/WRC/v0';
local subdir = 'USDA';

local ee_const = import 'earthengine_const.libsonnet';
local ee = import 'earthengine.libsonnet';
local spdx = import 'spdx.libsonnet';
local units = import 'units.libsonnet';

local license = spdx.cc_by_4_0;

local basename = std.strReplace(id, '/', '_');
local base_filename = basename + '.json';
local self_ee_catalog_url = ee_const.ee_catalog_url + basename;

{
  stac_version: ee_const.stac_version,
  type: ee_const.stac_type.collection,
  stac_extensions: [
    ee_const.ext_eo,
    ee_const.ext_sci,
  ],
  id: id,
  title: 'Wildfire Risk to Communities v0',
  'gee:type': ee_const.gee_type.image_collection,
  description: |||
    This dataset depicts components of wildfire risk for all lands in the United
    States that: 1) are landscape-wide (i.e., measurable at every pixel across 
    the landscape); and 2) represent in situ risk - risk at the location where
    the adverse effects take place on the landscape.

    National wildfire hazard datasets of annual burn probability and fire
    intensity, generated by the USDA Forest Service, Rocky Mountain Researc
    Station and Pyrologix LLC, form the foundation of the Wildfire Risk to
    Communities data. Vegetation and wildland fuels data from LANDFIRE 2020
    (version 2.2.0) were used as input to two different but related geospatial
    fire simulation systems. Annual burn probability was produced with the USFS
    geospatial fire simulator (FSim) at a relatively coarse cell size of 270
    meters (m). The burn probability raster data was upsampled to the native
    30 m resolution of the LANDFIRE fuel and vegetation data, to bring the data
    down to a finer resolution more useful for assessing hazard and risk to
    communities. In this upsampling process, the provider also spread values of
    modeled burn probability into developed areas represented in LANDFIRE fuels
    data as non-burnable.

    Burn probability rasters represent landscape
    conditions as of the end of 2020. Fire intensity characteristics were
    modeled at 30 m resolution using a process that performs a comprehensive
    set of FlamMap runs spanning the full range of weather-related
    characteristics that occur during a fire season and then integrates those
    runs into a variety of results based on the likelihood of those weather
    types occurring. Before the fire intensity modeling, the LANDFIRE 2020 data
    were updated to reflect fuels disturbances occurring in 2021 and 2022. As
    such, the fire intensity datasets represent landscape conditions as of the
    end of 2022.
  |||,
  license: license.id,
  links: ee.standardLinks(subdir, id),
  'gee:categories': ['fire'],
  keywords: [
    'fire',
    'wildfire',
    'burn',
    'usda',
  ],
  providers: [
    ee.producer_provider(
      'USDA Forest Service Research Data Archive',
       'https://www.fs.usda.gov/rds/archive/catalog/RDS-2020-0016-2'),
    ee.host_provider(self_ee_catalog_url),
  ],
  extent: ee.extent(-180.0, -67.933, 18.854, 63.904,
                    '2020-12-31T00:00:00Z', '2022-12-31T00:00:00Z'),
  summaries: {
    gsd: [30],
    'eo:bands': [
      {
        name: 'BP',
        description: 'Annual Burn Probability.'
      },
      {
        name: 'CFL',
        description: 'Conditional Flame Length; mean flame length for fire burning in direction of maximum spread if a fire were to occur. Avg. measure of wildfire intensity.',
        'gee:units': units.foot
      },
      {
        name: 'CRPS',
        description: 'Conditional Risk to Potential Structures; potential consequences of fire to a home at a given location, if a fire occurs there and if a home were located there.'
      },
      {
        name: 'Exposure',
        description: 'Measure of how exposed a housing unit would be to wildfire. A value of 1 is "direct" exposure. Values between 0 and 1 represent "indirect" exposure, with higher values representing closer proximity to directly exposed areas'
      },
      {
        name: 'FLEP4',
        description: 'Flame Length Exceedance Probability - 4 ft; conditional probability that flame length at a pixel will exceed 4 feet if a fire occurs; indicates the potential for moderate to high wildfire intensity.'
      },
      {
        name: 'FLEP8',
        description: 'Farm Length Exceedance Probability - 8 ft; conditional probability that flame length at a pixel will exceed 8 feet if a fire occurs; indicates the potential for high wildfire intensity.'
      },
      {
        name: 'RPS',
        description: 'Risk to Potential Structures; relative risk to a house if one existed at that location.'
      },
      {
        name: 'WHP',
        description: 'Wildfire Hazard Potential index.'
      }
    ],
    BP: {minimum: 0, maximum: 0.14, 'gee:estimated_range': false},
    CFL: {minimum: 0, maximum: 861.7, 'gee:estimated_range': false},
    CRPS: {minimum: 0, maximum: 100, 'gee:estimated_range': false},
    Exposure: {minimum: 0, maximum: 1, 'gee:estimated_range': false},
    FLEP4: {minimum: 0, maximum: 1, 'gee:estimated_range': false},
    FLEP8: {minimum: 0, maximum: 1, 'gee:estimated_range': false},
    RPS: {minimum: 0, maximum: 13.2, 'gee:estimated_range': false},
    WHP: {minimum: 0, maximum: 99.853, 'gee:estimated_range': false},
    'gee:visualizations': [
      {
        display_name: 'Annual burn probability',
        lookat: {lon: -73.9958, lat: 40.7278, zoom: 15},
        image_visualization: {
          band_vis: {min: [0], max: [0.14], bands: ['BP']},
        },
      },
    ],
  },
  'sci:doi': '10.2737/RDS-2020-0016-2',
  'sci:citation': |||
    Scott, Joe H.; Dillon, Gregory K.; Jaffe, Melissa R.; Vogler, Kevin C.;
    Olszewski, Julia H.; Callahan, Michael N.; Karau, Eva C.; Lazarz,
    Mitchell T.; Short, Karen C.; Riley, Karin L.; Finney, Mark A.; Grenfell,
    Isaac C. 2024. Wildfire Risk to Communities: Spatial datasets of
    landscape-wide wildfire risk components for the United States. 2nd Edition.
    Fort Collins, CO: Forest Service Research Data Archive.
    [doi:10.2737/RDS-2020-0016-2](https://doi.org/10.2737/RDS-2020-0016-2)

  |||,

  'gee:terms_of_use': |||
    Data publications are made freely available to the public under our data
    use agreement outlining conditions of use such as redistribution,
    citation, notification, and distribution liability. The 
    [Open Access - Data Use Agreement](https://www.fs.usda.gov/rds/archive/datauseinfo/open)
    is implicitly agreed to by anyone acquiring data from this repository.
    Formally, Archive-published datasets are released under the Creative Commons
    CC-BY license structure. This allows for broad use and re-use, while
    preserving the expectation of citation of the data publication to document
    that use and credit the intellectual work of the author(s).

  |||,
}
