local id = 'projects/forestdatapartnership/assets/palm/model_2025b';
local subdir = 'forestdatapartnership';

local ee_const = import 'earthengine_const.libsonnet';
local ee = import 'earthengine.libsonnet';
local spdx = import 'spdx.libsonnet';
local units = import 'units.libsonnet';

local license = spdx.cc_by_4_0;

local version = '2025b';

local basename = std.strReplace(id, '/', '_');
local base_filename = basename + '.json';
local self_ee_catalog_url = ee_const.ee_catalog_url + basename;
local catalog_subdir_url = ee_const.catalog_base + subdir + '/';
local parent_url = catalog_subdir_url + 'catalog.json';
local self_url = catalog_subdir_url + base_filename;

{
  stac_version: ee_const.stac_version,
  type: ee_const.stac_type.collection,
  stac_extensions: [
    ee_const.ext_eo,
    ee_const.ext_sci,
    ee_const.ext_ver,
  ],
  id: id,
  version: version,
  title: 'Palm Probability model ' + version,
  'gee:type': ee_const.gee_type.image_collection,
  description: |||

    **Note: This dataset is not yet peer-reviewed. Please see this
    [GitHub README](https://github.com/google/forest-data-partnership/tree/main/models/v2025)
    for more information.**

    This image collection provides estimated per-pixel probability that the
    underlying area is occupied by the commodity.  The probability estimates are
    provided at 10 meter resolution, and have been generated by a machine
    learning model. For details, see the technical documentation on the
    [Forest Data Partnership repo](https://github.com/google/forest-data-partnership/tree/main)
    on Github.

    The primary purpose of this image collection is to support the mission of
    the [Forest Data Partnership](https://www.fao.org/in-action/forest-data-partnership) which
    aims to halt and reverse forest loss from commodity production by
    collaboratively improving global monitoring, supply chain tracking, and
    restoration.

    This dataset currently covers the pan-tropical region.

    This community data product is meant to evolve over time, as more data
    becomes available from the community and the model used to produce the maps
    continuously improves. If you would like to provide general feedback or
    additional datasets to improve these layers, please reach out through
    [this form](https://goo.gle/fdap-data).

    Limitations: See the 
    [GitHub README](https://github.com/google/forest-data-partnership/tree/main/models/v2025).

  |||,
  license: license.id,
  links: ee.standardLinks(subdir, id),
  'gee:categories': ['agriculture'],
  keywords: [
    'eudr',
    'biodiversity',
    'conservation',
    'crop',
    'landuse',
    'palm',
    'plantation',
    'pre_review',
  ],
  providers: [
    ee.producer_provider(
      'Produced by Google for the Forest Data Partnership',
      'https://www.fao.org/in-action/forest-data-partnership'
    ),
    ee.host_provider(self_ee_catalog_url),
  ],
  extent: ee.extent_global('2020-01-01T00:00:00Z', '2024-12-31T23:59:59Z'),
  summaries: {
    'eo:bands': [
      {
        name: 'probability',
        description: |||
          Probability that the pixel includes palm trees for the given year.
        |||,
      },
    ],
    gsd: [
      10.0,
    ],
    probability: { minimum: 0, maximum: 1, 'gee:estimated_range': false },
    // One or more band visualizations.
    'gee:visualizations': [
      // Example with one band.
      {
        display_name: 'Predicted probability of palm presence',
        lookat: { lon: -7, lat: 7, zoom: 6 },
        image_visualization: { band_vis: { min: [0.5], bands: ['probability'] } },
      },
    ],
  },
  'sci:citation': |||
    Forest Data Partnership. 2026. Community models 2025b. [Online](https://github.com/google/forest-data-partnership/tree/main/models/v2025/README.md)
  |||,
  'gee:terms_of_use': |||

    Use of the dataset is subject to the
    CC-BY 4.0 license and requires the following attribution:
    "Produced by Google for the Forest Data Partnership".

  |||,
}
