local id = 'JRC/GHSL/P2023A/GHS_SMOD';
local versions = import 'versions.libsonnet';
local version_table = import 'templates/jrc_smod_pop_versions.libsonnet';

local subdir = 'JRC';

local ee_const = import 'earthengine_const.libsonnet';
local ee = import 'earthengine.libsonnet';
local spdx = import 'spdx.libsonnet';
local version_config = versions(subdir, version_table, id);
local version = version_config.version;

local license = spdx.proprietary;

{
  stac_version: ee_const.stac_version,
  type: ee_const.stac_type.collection,
  stac_extensions: [
    ee_const.ext_eo,
    ee_const.ext_sci,
    ee_const.ext_ver,
  ],
  id: id,
  title: 'GHSL: Degree of Urbanization 1975-2030 (P2023A)',
  version: version,
  'gee:type': ee_const.gee_type.image_collection,
  description: |||
    This raster dataset represents a global, multitemporal rural-urban
    classification, applying the "Degree of Urbanisation" stage I methodology
    recommended by UN Statistical Commission, based on global gridded population
    and built-up surface data generated by the GHSL project for the epochs
    1975-2030 in 5-year intervals. The Degree of Urbanisation layers have been
    generated by integrating information on built-up surface extracted from
    Landsat and Sentinel-2 data [GHS-BUILT-S R2023]
    (https://developers.google.com/earth-engine/datasets/catalog/JRC_GHSL_P2023A_GHS_BUILT_S),
    and gridded population data derived from CIESIN GPW v4.11 [GHS-POP R2023]
    (https://developers.google.com/earth-engine/datasets/catalog/JRC_GHSL_P2023A_GHS_POP).
    This product is an update of the data released in 2022 based on the updates
    of the GHS-BUILT-S and GHS-POP. The Settlement Model is provided at the
    detailed level (Second Level - L2). The first-level classification can be
    obtained by aggregating L2.

    The complete information about the GHSL main products can be found in the
    [GHSL Data Package 2023 report]
    (https://ghsl.jrc.ec.europa.eu/documents/GHSL_Data_Package_2023.pdf?t=1683540422)

    The Global Human Settlement Layer (GHSL) project is supported by the European
    Commission, Joint Research Center, and Directorate-General for Regional and
    Urban Policy.
  |||,
  license: license.id,
  links: ee.standardLinks(subdir, id) + version_config.version_links,
  keywords: [
    'ghsl',
    'jrc',
    'settlement',
    'smod',
    'sdg',
    'urban_gradient',
  ],
  providers: [
    ee.producer_provider('EC JRC', 'https://ghsl.jrc.ec.europa.eu/ghs_smod2023.php'),
    ee.host_provider(version_config.ee_catalog_url),
  ],
  extent: ee.extent_global('1975-01-01T00:00:00Z', '2030-12-31T00:00:00Z'),
  summaries: {
    gsd: [
      1000.0,
    ],
    'eo:bands': [
      {
        name: 'smod_code',
        description: 'Degree of urbanization',
        'gee:classes': [
          {
            color: '000000',
            description: 'No Data',
            value: -200,
          },
          {
            value: 10,
            color: '7ab6f5',
            description: 'Water',
          },
          {
            value: 11,
            color: 'cdf57a',
            description: 'Very low density rural',
          },
          {
            value: 12,
            color: 'abcd66',
            description: 'Low density rural',
          },
          {
            value: 13,
            color: '375623',
            description: 'Rural cluster',
          },
          {
            value: 21,
            color: 'ffff00',
            description: 'Suburban or peri-urban',
          },
          {
            value: 22,
            color: 'a87000',
            description: 'Semi-dense urban cluster',
          },
          {
            value: 23,
            color: '732600',
            description: 'Dense urban cluster',
          },
         {
            value: 30,
            color: 'ff0000',
            description: 'Urban centre',
          },
        ],
      },
    ],
    'gee:visualizations': [
      {
        display_name: 'Degree of Urbanization',
        lookat: {
          lat: 31.13,
          lon: 114.96,
          zoom: 4,
        },
        image_visualization: {
          band_vis: {
            min: [
              0.0,
            ],
            max: [
              3.0,
            ],
            palette: [
              '000000',
              '448564',
              '70daa4',
              'ffffff',
            ],
            bands: [
              'smod_code',
            ],
          },
        },
      },
    ],
  },
  'sci:citation': |||
    Schiavina, Marcello; Melchiorri, Michele; Pesaresi, Martino (2023): 
    GHS-SMOD R2023A - GHS settlement layers, application of the Degree of
    Urbanisation methodology (stage I) to GHS-POP R2023A and GHS-BUILT-S R2023A,
    multitemporal (1975-2030). European Commission, Joint Research Centre (JRC)
    [PID: http://data.europa.eu/89h/a0df7a6f-49de-46ea-9bde-563437a6e2ba](http://data.europa.eu/89h/a0df7a6f-49de-46ea-9bde-563437a6e2ba)
    [doi:10.2905/A0DF7A6F-49DE-46EA-9BDE-563437A6E2BA](https://doi.org/10.2905/A0DF7A6F-49DE-46EA-9BDE-563437A6E2BA)
  |||,
  'sci:doi': '10.2905/A0DF7A6F-49DE-46EA-9BDE-563437A6E2BA',
  'gee:terms_of_use': |||
    The GHSL has been produced by the European Commission Joint Research Centre
    as open and free data. Reuse is authorised, provided the source is
    acknowledged. For more information, please read the use conditions ([European
    Commission Reuse and Copyright Notice](https://ec.europa.eu/info/legal-notice_en)).
  |||,
}
