"""Checks for example scripts.

- All datasets must have a dataset example script
- All new datasets must have a _preview.js script that uses
  `print(ui.Thumbnail()` to create a 256x256 PNG preview image.
- ee.Tables must have a FeatureView example script, except when
  gee:skip_featureview_generation is set to true
"""

# TODO(schwehr): Add a tree check to find unused scripts.
# TODO(schwehr): Add a generate_examples script and add a message to use it.

import pathlib
from typing import Iterator

from checker import stac


_EXCEPTIONS_RAW = frozenset((
    'MODIS_MCD43A1',
    'MODIS_MCD43A2',
    'MODIS_MCD43A4',
    'MODIS_MCD43A4_BAI',
    'MODIS_MCD43A4_EVI',
    'MODIS_MCD43A4_NDSI',
    'MODIS_MCD43A4_NDVI',
    'MODIS_MCD43A4_NDWI',
    'MODIS_MOD09A1',
    'MODIS_MOD09GA',
    'MODIS_MOD09GA_BAI',
    'MODIS_MOD09GA_EVI',
    'MODIS_MOD09GA_NDSI',
    'MODIS_MOD09GA_NDVI',
    'MODIS_MOD09GA_NDWI',
    'MODIS_MOD09GQ',
    'MODIS_MOD09Q1',
    'MODIS_MOD11A1',
    'MODIS_MOD11A2',
    'MODIS_MOD13Q1',
    'MODIS_MYD09A1',
    'MODIS_MYD09GA',
    'MODIS_MYD09GA_BAI',
    'MODIS_MYD09GA_EVI',
    'MODIS_MYD09GA_NDSI',
    'MODIS_MYD09GA_NDVI',
    'MODIS_MYD09GA_NDWI',
    'MODIS_MYD09GQ',
    'MODIS_MYD09Q1',
    'MODIS_MYD10A1',
    'MODIS_MYD11A1',
    'MODIS_MYD11A2',
    'MODIS_MYD13Q1',
    ))
_EXCEPTIONS = frozenset({x + '.js' for x in _EXCEPTIONS_RAW})

_FEATURE_VIEW_EXCEPTIONS = frozenset({
    'JRC/JRC_LUCAS_HARMO_COPERNICUS_POLYGONS_V1_2018_FeatureView.js',
    'LARSE/LARSE_GEDI_GEDI02_A_002_INDEX_FeatureView.js',
    'LARSE/LARSE_GEDI_GEDI02_B_002_INDEX_FeatureView.js',
    'LARSE/LARSE_GEDI_GEDI04_A_002_INDEX_FeatureView.js',
    'TIGER/TIGER_2010_BG_FeatureView.js',
    'WWF/WWF_HydroATLAS_v1_Basins_level12_FeatureView.js',
    'WWF/WWF_HydroATLAS_v1_Basins_level11_FeatureView.js',
    'WWF/WWF_HydroATLAS_v1_Basins_level10_FeatureView.js',
    'WWF/WWF_HydroATLAS_v1_Basins_level09_FeatureView.js',
    'WWF/WWF_HydroATLAS_v1_Basins_level08_FeatureView.js',
    'WWF/WWF_HydroATLAS_v1_Basins_level07_FeatureView.js',
    'WWF/WWF_HydroATLAS_v1_Basins_level06_FeatureView.js',
    'WWF/WWF_HydroATLAS_v1_Basins_level05_FeatureView.js',
    'WWF/WWF_HydroATLAS_v1_Basins_level04_FeatureView.js',
    'WWF/WWF_HydroATLAS_v1_Basins_level03_FeatureView.js',
})

# TODO(schwehr): Remove entries as they are backfilled.
_PREVIEW_EXCEPTIONS_LIST = [
    'AAFC/AAFC_ACI',
    'ACA/ACA_reef_habitat_v1_0',
    'AHN/AHN_AHN2_05M_INT',
    'AHN/AHN_AHN2_05M_NON',
    'AHN/AHN_AHN2_05M_RUW',
    'ASTER/ASTER_AST_L1T_003',
    'AU/AU_GA_AUSTRALIA_5M_DEM',
    'AU/AU_GA_DEM_1SEC_v10_DEM-H',
    'AU/AU_GA_DEM_1SEC_v10_DEM-S',
    'BIOPAMA/BIOPAMA_GlobalOilPalm_v1',
    'BLM/BLM_AIM_v1_TerrADat_TerrestrialAIM',
    'BNU/BNU_FGS_CCNL_v1',
    'CAS/CAS_IGSNRR_PML_V2',
    'CAS/CAS_IGSNRR_PML_V2_v017',
    'CGIAR/CGIAR_SRTM90_V4',
    'CIESIN/CIESIN_GPWv411_GPW_Basic_Demographic_Characteristics',
    'CIESIN/CIESIN_GPWv411_GPW_Data_Context',
    'CIESIN/CIESIN_GPWv411_GPW_Land_Area',
    'CIESIN/CIESIN_GPWv411_GPW_Mean_Administrative_Unit_Area',
    'CIESIN/CIESIN_GPWv411_GPW_National_Identifier_Grid',
    'CIESIN/CIESIN_GPWv411_GPW_Population_Count',
    'CIESIN/CIESIN_GPWv411_GPW_Population_Density',
    'CIESIN/CIESIN_GPWv411_GPW_UNWPP-Adjusted_Population_Count',
    'CIESIN/CIESIN_GPWv411_GPW_UNWPP-Adjusted_Population_Density',
    'CIESIN/CIESIN_GPWv411_GPW_Water_Area',
    'CIESIN/CIESIN_GPWv411_GPW_Water_Mask',
    'CIESIN/CIESIN_GPWv4_ancillary-data-grids',
    'CIESIN/CIESIN_GPWv4_population-count',
    'CIESIN/CIESIN_GPWv4_population-density',
    'CIESIN/CIESIN_GPWv4_unwpp-adjusted-population-count',
    'CIESIN/CIESIN_GPWv4_unwpp-adjusted-population-density',
    'COPERNICUS/COPERNICUS_CORINE_V18_5_1_100m',
    'COPERNICUS/COPERNICUS_CORINE_V20_100m',
    'COPERNICUS/COPERNICUS_DEM_GLO30',
    'COPERNICUS/COPERNICUS_Landcover_100m_Proba-V-C3_Global',
    'COPERNICUS/COPERNICUS_Landcover_100m_Proba-V_Global',
    'COPERNICUS/COPERNICUS_S1_GRD',
    'COPERNICUS/COPERNICUS_S2',
    'COPERNICUS/COPERNICUS_S2_CLOUD_PROBABILITY',
    'COPERNICUS/COPERNICUS_S2_HARMONIZED',
    'COPERNICUS/COPERNICUS_S2_SR',
    'COPERNICUS/COPERNICUS_S2_SR_HARMONIZED',
    'COPERNICUS/COPERNICUS_S3_OLCI',
    'COPERNICUS/COPERNICUS_S5P_NRTI_L3_AER_AI',
    'COPERNICUS/COPERNICUS_S5P_NRTI_L3_AER_LH',
    'COPERNICUS/COPERNICUS_S5P_NRTI_L3_CLOUD',
    'COPERNICUS/COPERNICUS_S5P_NRTI_L3_CO',
    'COPERNICUS/COPERNICUS_S5P_NRTI_L3_HCHO',
    'COPERNICUS/COPERNICUS_S5P_NRTI_L3_NO2',
    'COPERNICUS/COPERNICUS_S5P_NRTI_L3_O3',
    'COPERNICUS/COPERNICUS_S5P_NRTI_L3_SO2',
    'COPERNICUS/COPERNICUS_S5P_OFFL_L3_AER_AI',
    'COPERNICUS/COPERNICUS_S5P_OFFL_L3_AER_LH',
    'COPERNICUS/COPERNICUS_S5P_OFFL_L3_CH4',
    'COPERNICUS/COPERNICUS_S5P_OFFL_L3_CLOUD',
    'COPERNICUS/COPERNICUS_S5P_OFFL_L3_CO',
    'COPERNICUS/COPERNICUS_S5P_OFFL_L3_HCHO',
    'COPERNICUS/COPERNICUS_S5P_OFFL_L3_NO2',
    'COPERNICUS/COPERNICUS_S5P_OFFL_L3_O3',
    'COPERNICUS/COPERNICUS_S5P_OFFL_L3_O3_TCL',
    'COPERNICUS/COPERNICUS_S5P_OFFL_L3_SO2',
    'CPOM/CPOM_CryoSat2_ANTARCTICA_DEM',
    'CSIRO/CSIRO_SLGA',
    'CSP/CSP_ERGo_1_0_Global_ALOS_CHILI',
    'CSP/CSP_ERGo_1_0_Global_ALOS_landforms',
    'CSP/CSP_ERGo_1_0_Global_ALOS_mTPI',
    'CSP/CSP_ERGo_1_0_Global_ALOS_topoDiversity',
    'CSP/CSP_ERGo_1_0_Global_SRTM_CHILI',
    'CSP/CSP_ERGo_1_0_Global_SRTM_landforms',
    'CSP/CSP_ERGo_1_0_Global_SRTM_mTPI',
    'CSP/CSP_ERGo_1_0_Global_SRTM_topoDiversity',
    'CSP/CSP_ERGo_1_0_US_CHILI',
    'CSP/CSP_ERGo_1_0_US_landforms',
    'CSP/CSP_ERGo_1_0_US_lithology',
    'CSP/CSP_ERGo_1_0_US_mTPI',
    'CSP/CSP_ERGo_1_0_US_physioDiversity',
    'CSP/CSP_ERGo_1_0_US_physiography',
    'CSP/CSP_ERGo_1_0_US_topoDiversity',
    'CSP/CSP_HM_GlobalHumanModification',
    'DLR/DLR_WSF_WSF2015_v1',
    'DOE/DOE_ORNL_LandScan_HD_Ukraine_202201',
    'ECMWF/ECMWF_CAMS_NRT',
    'ECMWF/ECMWF_ERA5_DAILY',
    'ECMWF/ECMWF_ERA5_LAND_DAILY_AGGR',
    'ECMWF/ECMWF_ERA5_LAND_HOURLY',
    'ECMWF/ECMWF_ERA5_LAND_MONTHLY',
    'ECMWF/ECMWF_ERA5_LAND_MONTHLY_AGGR',
    'ECMWF/ECMWF_ERA5_LAND_MONTHLY_BY_HOUR',
    'ECMWF/ECMWF_ERA5_MONTHLY',
    'EO1/EO1_HYPERION',
    'EPA/EPA_Ecoregions_2013_L3',
    'EPA/EPA_Ecoregions_2013_L4',
    'ESA/ESA_CCI_FireCCI_5_1',
    'ESA/ESA_GLOBCOVER_L4_200901_200912_V2_3',
    'ESA/ESA_WorldCover_v100',
    'ESA/ESA_WorldCover_v200',
    'FAO/FAO_GAUL_2015_level0',
    'FAO/FAO_GAUL_2015_level1',
    'FAO/FAO_GAUL_2015_level2',
    'FAO/FAO_GAUL_SIMPLIFIED_500m_2015_level0',
    'FAO/FAO_GAUL_SIMPLIFIED_500m_2015_level1',
    'FAO/FAO_GAUL_SIMPLIFIED_500m_2015_level2',
    'FAO/FAO_GHG_1_DROSA_A',
    'FAO/FAO_GHG_1_DROSE_A',
    'FAO/FAO_SOFO_1_FPP',
    'FAO/FAO_SOFO_1_TPP',
    'FAO/FAO_WAPOR_2_L1_AETI_D',
    'FAO/FAO_WAPOR_2_L1_E_D',
    'FAO/FAO_WAPOR_2_L1_I_D',
    'FAO/FAO_WAPOR_2_L1_NPP_D',
    'FAO/FAO_WAPOR_2_L1_RET_D',
    'FAO/FAO_WAPOR_2_L1_RET_E',
    'FAO/FAO_WAPOR_2_L1_T_D',
    'FIRMS/FIRMS',
    'FORMA/FORMA_FORMA_500m',
    'Finland/Finland_MAVI_VV_50cm',
    'Finland/Finland_SMK_VV_50cm',
    'Finland/Finland_SMK_V_50cm',
    'GFW/GFW_GFF_V1_fishing_hours',
    'GFW/GFW_GFF_V1_vessel_hours',
    'GLCF/GLCF_GLS_TCC',
    'GLCF/GLCF_GLS_WATER',
    'GLIMS/GLIMS_2016',
    'GLIMS/GLIMS_20171027',
    'GLIMS/GLIMS_20210914',
    'GLOBAL_FLOOD_DB/GLOBAL_FLOOD_DB_MODIS_EVENTS_V1',
    'GOOGLE/GOOGLE_DYNAMICWORLD_V1',
    'GOOGLE/GOOGLE_Research_open-buildings_v1_polygons',
    'GOOGLE/GOOGLE_Research_open-buildings_v2_polygons',
    'GRIDMET/GRIDMET_DROUGHT',
    'Germany/Germany_Brandenburg_orthos_20cm',
    'HYCOM/HYCOM_GLBu0_08_sea_surface_elevation',
    'HYCOM/HYCOM_GLBu0_08_sea_temp_salinity',
    'HYCOM/HYCOM_GLBu0_08_sea_water_velocity',
    'HYCOM/HYCOM_sea_surface_elevation',
    'HYCOM/HYCOM_sea_temp_salinity',
    'HYCOM/HYCOM_sea_water_velocity',
    'IDAHO_EPSCOR/IDAHO_EPSCOR_GRIDMET',
    'IDAHO_EPSCOR/IDAHO_EPSCOR_MACAv2_METDATA',  # go/NOTYPO
    'IDAHO_EPSCOR/IDAHO_EPSCOR_MACAv2_METDATA_MONTHLY',  # go/NOTYPO
    'IDAHO_EPSCOR/IDAHO_EPSCOR_PDSI',
    'IDAHO_EPSCOR/IDAHO_EPSCOR_TERRACLIMATE',
    'IGN/IGN_RGE_ALTI_1M_2_0',
    'ISDASOIL/ISDASOIL_Africa_v1_aluminium_extractable',
    'ISDASOIL/ISDASOIL_Africa_v1_bedrock_depth',
    'ISDASOIL/ISDASOIL_Africa_v1_bulk_density',
    'ISDASOIL/ISDASOIL_Africa_v1_calcium_extractable',
    'ISDASOIL/ISDASOIL_Africa_v1_carbon_organic',
    'ISDASOIL/ISDASOIL_Africa_v1_carbon_total',
    'ISDASOIL/ISDASOIL_Africa_v1_cation_exchange_capacity',
    'ISDASOIL/ISDASOIL_Africa_v1_clay_content',
    'ISDASOIL/ISDASOIL_Africa_v1_fcc',
    'ISDASOIL/ISDASOIL_Africa_v1_iron_extractable',
    'ISDASOIL/ISDASOIL_Africa_v1_magnesium_extractable',
    'ISDASOIL/ISDASOIL_Africa_v1_nitrogen_total',
    'ISDASOIL/ISDASOIL_Africa_v1_ph',
    'ISDASOIL/ISDASOIL_Africa_v1_phosphorus_extractable',
    'ISDASOIL/ISDASOIL_Africa_v1_potassium_extractable',
    'ISDASOIL/ISDASOIL_Africa_v1_sand_content',
    'ISDASOIL/ISDASOIL_Africa_v1_silt_content',
    'ISDASOIL/ISDASOIL_Africa_v1_stone_content',
    'ISDASOIL/ISDASOIL_Africa_v1_sulphur_extractable',
    'ISDASOIL/ISDASOIL_Africa_v1_texture_class',
    'ISDASOIL/ISDASOIL_Africa_v1_zinc_extractable',
    'JAXA/JAXA_ALOS_AVNIR-2_ORI',
    'JAXA/JAXA_ALOS_AW3D30_V1_1',
    'JAXA/JAXA_ALOS_AW3D30_V2_1',
    'JAXA/JAXA_ALOS_AW3D30_V2_2',
    'JAXA/JAXA_ALOS_AW3D30_V3_2',
    'JAXA/JAXA_ALOS_PALSAR-2_Level2_2_ScanSAR',
    'JAXA/JAXA_ALOS_PALSAR_YEARLY_FNF',
    'JAXA/JAXA_ALOS_PALSAR_YEARLY_FNF4',
    'JAXA/JAXA_ALOS_PALSAR_YEARLY_SAR',
    'JAXA/JAXA_ALOS_PALSAR_YEARLY_SAR_EPOCH',
    'JAXA/JAXA_GCOM-C_L3_LAND_LAI_V1',
    'JAXA/JAXA_GCOM-C_L3_LAND_LAI_V2',
    'JAXA/JAXA_GCOM-C_L3_LAND_LAI_V3',
    'JAXA/JAXA_GCOM-C_L3_LAND_LST_V1',
    'JAXA/JAXA_GCOM-C_L3_LAND_LST_V2',
    'JAXA/JAXA_GCOM-C_L3_LAND_LST_V3',
    'JAXA/JAXA_GCOM-C_L3_OCEAN_CHLA_V1',
    'JAXA/JAXA_GCOM-C_L3_OCEAN_CHLA_V2',
    'JAXA/JAXA_GCOM-C_L3_OCEAN_CHLA_V3',
    'JAXA/JAXA_GCOM-C_L3_OCEAN_SST_V1',
    'JAXA/JAXA_GCOM-C_L3_OCEAN_SST_V2',
    'JAXA/JAXA_GCOM-C_L3_OCEAN_SST_V3',
    'JAXA/JAXA_GPM_L3_GSMaP_v6_operational',
    'JAXA/JAXA_GPM_L3_GSMaP_v6_reanalysis',
    'JCU/JCU_Murray_GIC_global_tidal_wetland_change_2019',
    'JRC/JRC_D5_EUCROPMAP_V1',
    'JRC/JRC_GHSL_P2016_BUILT_LDSMT_GLOBE_V1',
    'JRC/JRC_GHSL_P2016_POP_GPW_GLOBE_V1',
    'JRC/JRC_GHSL_P2016_SMOD_POP_GLOBE_V1',
    'JRC/JRC_GSW1_0_GlobalSurfaceWater',
    'JRC/JRC_GSW1_0_Metadata',
    'JRC/JRC_GSW1_0_MonthlyHistory',
    'JRC/JRC_GSW1_0_MonthlyRecurrence',
    'JRC/JRC_GSW1_0_YearlyHistory',
    'JRC/JRC_GSW1_1_GlobalSurfaceWater',
    'JRC/JRC_GSW1_1_Metadata',
    'JRC/JRC_GSW1_1_MonthlyHistory',
    'JRC/JRC_GSW1_1_MonthlyRecurrence',
    'JRC/JRC_GSW1_1_YearlyHistory',
    'JRC/JRC_GSW1_2_GlobalSurfaceWater',
    'JRC/JRC_GSW1_2_Metadata',
    'JRC/JRC_GSW1_2_MonthlyHistory',
    'JRC/JRC_GSW1_2_MonthlyRecurrence',
    'JRC/JRC_GSW1_2_YearlyHistory',
    'JRC/JRC_GSW1_3_GlobalSurfaceWater',
    'JRC/JRC_GSW1_3_Metadata',
    'JRC/JRC_GSW1_3_MonthlyHistory',
    'JRC/JRC_GSW1_3_MonthlyRecurrence',
    'JRC/JRC_GSW1_3_YearlyHistory',
    'JRC/JRC_GSW1_4_GlobalSurfaceWater',
    'JRC/JRC_GSW1_4_Metadata',
    'JRC/JRC_GSW1_4_MonthlyHistory',
    'JRC/JRC_GSW1_4_MonthlyRecurrence',
    'JRC/JRC_GSW1_4_YearlyHistory',
    'JRC/JRC_GWIS_GlobFire_v2_DailyPerimeters',
    'JRC/JRC_GWIS_GlobFire_v2_FinalPerimeters',
    'JRC/JRC_LUCAS_HARMO_COPERNICUS_POLYGONS_V1_2018',
    'JRC/JRC_LUCAS_HARMO_THLOC_V1',
    'KNTU/KNTU_LiDARLab_IranLandCover_V1',
    'LANDFIRE/LANDFIRE_Fire_FRG_v1_2_0',
    'LANDFIRE/LANDFIRE_Fire_MFRI_v1_2_0',
    'LANDFIRE/LANDFIRE_Fire_PLS_v1_2_0',
    'LANDFIRE/LANDFIRE_Fire_PMS_v1_2_0',
    'LANDFIRE/LANDFIRE_Fire_PRS_v1_2_0',
    'LANDFIRE/LANDFIRE_Fire_SClass_v1_4_0',
    'LANDFIRE/LANDFIRE_Fire_VCC_v1_4_0',
    'LANDFIRE/LANDFIRE_Fire_VDep_v1_4_0',
    'LANDFIRE/LANDFIRE_Vegetation_BPS_v1_4_0',
    'LANDFIRE/LANDFIRE_Vegetation_ESP_v1_2_0_AK',
    'LANDFIRE/LANDFIRE_Vegetation_ESP_v1_2_0_CONUS',
    'LANDFIRE/LANDFIRE_Vegetation_ESP_v1_2_0_HI',
    'LANDFIRE/LANDFIRE_Vegetation_EVC_v1_4_0',
    'LANDFIRE/LANDFIRE_Vegetation_EVH_v1_4_0',
    'LANDFIRE/LANDFIRE_Vegetation_EVT_v1_4_0',
    'LANDSAT/LANDSAT_GLS1975',
    'LANDSAT/LANDSAT_GLS1975_MOSAIC',
    'LANDSAT/LANDSAT_GLS2005',
    'LANDSAT/LANDSAT_GLS2005_L5',
    'LANDSAT/LANDSAT_GLS2005_L7',
    'LANDSAT/LANDSAT_LC08_C02_T1',
    'LANDSAT/LANDSAT_LC08_C02_T1_L2',
    'LANDSAT/LANDSAT_LC08_C02_T1_RT',
    'LANDSAT/LANDSAT_LC08_C02_T1_RT_TOA',
    'LANDSAT/LANDSAT_LC08_C02_T1_TOA',
    'LANDSAT/LANDSAT_LC08_C02_T2',
    'LANDSAT/LANDSAT_LC08_C02_T2_L2',
    'LANDSAT/LANDSAT_LC08_C02_T2_TOA',
    'LANDSAT/LANDSAT_LC09_C02_T1',
    'LANDSAT/LANDSAT_LC09_C02_T1_L2',
    'LANDSAT/LANDSAT_LC09_C02_T1_TOA',
    'LANDSAT/LANDSAT_LC09_C02_T2',
    'LANDSAT/LANDSAT_LC09_C02_T2_L2',
    'LANDSAT/LANDSAT_LC09_C02_T2_TOA',
    'LANDSAT/LANDSAT_LE07_C02_T1',
    'LANDSAT/LANDSAT_LE07_C02_T1_L2',
    'LANDSAT/LANDSAT_LE07_C02_T1_RT',
    'LANDSAT/LANDSAT_LE07_C02_T1_RT_TOA',
    'LANDSAT/LANDSAT_LE07_C02_T1_TOA',
    'LANDSAT/LANDSAT_LE07_C02_T2',
    'LANDSAT/LANDSAT_LE07_C02_T2_L2',
    'LANDSAT/LANDSAT_LE07_C02_T2_TOA',
    'LANDSAT/LANDSAT_LM01_C01_T1',
    'LANDSAT/LANDSAT_LM01_C01_T2',
    'LANDSAT/LANDSAT_LM01_C02_T1',
    'LANDSAT/LANDSAT_LM01_C02_T2',
    'LANDSAT/LANDSAT_LM02_C01_T1',
    'LANDSAT/LANDSAT_LM02_C01_T2',
    'LANDSAT/LANDSAT_LM02_C02_T1',
    'LANDSAT/LANDSAT_LM02_C02_T2',
    'LANDSAT/LANDSAT_LM03_C01_T1',
    'LANDSAT/LANDSAT_LM03_C01_T2',
    'LANDSAT/LANDSAT_LM03_C02_T1',
    'LANDSAT/LANDSAT_LM03_C02_T2',
    'LANDSAT/LANDSAT_LM04_C01_T1',
    'LANDSAT/LANDSAT_LM04_C01_T2',
    'LANDSAT/LANDSAT_LM04_C02_T1',
    'LANDSAT/LANDSAT_LM04_C02_T2',
    'LANDSAT/LANDSAT_LM05_C01_T1',
    'LANDSAT/LANDSAT_LM05_C01_T2',
    'LANDSAT/LANDSAT_LM05_C02_T1',
    'LANDSAT/LANDSAT_LM05_C02_T2',
    'LANDSAT/LANDSAT_LT04_C02_T1',
    'LANDSAT/LANDSAT_LT04_C02_T1_L2',
    'LANDSAT/LANDSAT_LT04_C02_T1_TOA',
    'LANDSAT/LANDSAT_LT04_C02_T2',
    'LANDSAT/LANDSAT_LT04_C02_T2_L2',
    'LANDSAT/LANDSAT_LT04_C02_T2_TOA',
    'LANDSAT/LANDSAT_LT05_C02_T1',
    'LANDSAT/LANDSAT_LT05_C02_T1_L2',
    'LANDSAT/LANDSAT_LT05_C02_T1_TOA',
    'LANDSAT/LANDSAT_LT05_C02_T2',
    'LANDSAT/LANDSAT_LT05_C02_T2_L2',
    'LANDSAT/LANDSAT_LT05_C02_T2_TOA',
    'LANDSAT/LANDSAT_LT08_C01_T2',
    'LANDSAT/LANDSAT_MANGROVE_FORESTS',
    'LARSE/LARSE_GEDI_GEDI02_A_002',
    'LARSE/LARSE_GEDI_GEDI02_A_002_INDEX',
    'LARSE/LARSE_GEDI_GEDI02_A_002_MONTHLY',
    'LARSE/LARSE_GEDI_GEDI02_B_002',
    'LARSE/LARSE_GEDI_GEDI02_B_002_INDEX',
    'LARSE/LARSE_GEDI_GEDI02_B_002_MONTHLY',
    'LARSE/LARSE_GEDI_GEDI04_A_002',
    'LARSE/LARSE_GEDI_GEDI04_A_002_INDEX',
    'LARSE/LARSE_GEDI_GEDI04_A_002_MONTHLY',
    'LARSE/LARSE_GEDI_GEDI04_B_002',
    'Latvia/Latvia_Maamet_orthos_cir',
    'Latvia/Latvia_Maamet_orthos_rgb',
    'MERIT/MERIT_DEM_v1_0_3',
    'MERIT/MERIT_Hydro_reduced_v1_0_1',
    'MERIT/MERIT_Hydro_v1_0_1',
    'MODIS/MODIS_006_MCD12Q1',
    'MODIS/MODIS_006_MCD12Q2',
    'MODIS/MODIS_006_MCD15A3H',
    'MODIS/MODIS_006_MCD19A2_GRANULES',
    'MODIS/MODIS_006_MCD43A1',
    'MODIS/MODIS_006_MCD43A2',
    'MODIS/MODIS_006_MCD43A3',
    'MODIS/MODIS_006_MCD43A4',
    'MODIS/MODIS_006_MCD43C3',
    'MODIS/MODIS_006_MCD64A1',
    'MODIS/MODIS_006_MOD08_M3',
    'MODIS/MODIS_006_MOD09A1',
    'MODIS/MODIS_006_MOD09GA',
    'MODIS/MODIS_006_MOD09GQ',
    'MODIS/MODIS_006_MOD09Q1',
    'MODIS/MODIS_006_MOD10A1',
    'MODIS/MODIS_006_MOD11A1',
    'MODIS/MODIS_006_MOD11A2',
    'MODIS/MODIS_006_MOD13A1',
    'MODIS/MODIS_006_MOD13A2',
    'MODIS/MODIS_006_MOD13Q1',
    'MODIS/MODIS_006_MOD14A1',
    'MODIS/MODIS_006_MOD14A2',
    'MODIS/MODIS_006_MOD15A2H',
    'MODIS/MODIS_006_MOD16A2',
    'MODIS/MODIS_006_MOD17A2H',
    'MODIS/MODIS_006_MOD17A3H',
    'MODIS/MODIS_006_MOD17A3HGF',
    'MODIS/MODIS_006_MOD44B',
    'MODIS/MODIS_006_MOD44W',
    'MODIS/MODIS_006_MODOCGA',
    'MODIS/MODIS_006_MYD08_M3',
    'MODIS/MODIS_006_MYD09A1',
    'MODIS/MODIS_006_MYD09GA',
    'MODIS/MODIS_006_MYD09GQ',
    'MODIS/MODIS_006_MYD09Q1',
    'MODIS/MODIS_006_MYD10A1',
    'MODIS/MODIS_006_MYD11A1',
    'MODIS/MODIS_006_MYD11A2',
    'MODIS/MODIS_006_MYD13A1',
    'MODIS/MODIS_006_MYD13A2',
    'MODIS/MODIS_006_MYD13Q1',
    'MODIS/MODIS_006_MYD14A1',
    'MODIS/MODIS_006_MYD14A2',
    'MODIS/MODIS_006_MYD15A2H',
    'MODIS/MODIS_006_MYD17A2H',
    'MODIS/MODIS_006_MYD17A3H',
    'MODIS/MODIS_006_MYD17A3HGF',
    'MODIS/MODIS_006_MYDOCGA',
    'MODIS/MODIS_055_MOD17A3',
    'MODIS/MODIS_061_MCD12Q1',
    'MODIS/MODIS_061_MCD12Q2',
    'MODIS/MODIS_061_MCD15A3H',
    'MODIS/MODIS_061_MCD18C2',
    'MODIS/MODIS_061_MCD19A2_GRANULES',
    'MODIS/MODIS_061_MCD43A1',
    'MODIS/MODIS_061_MCD43A2',
    'MODIS/MODIS_061_MCD43A3',
    'MODIS/MODIS_061_MCD43A4',
    'MODIS/MODIS_061_MCD43C3',
    'MODIS/MODIS_061_MCD64A1',
    'MODIS/MODIS_061_MOD08_M3',
    'MODIS/MODIS_061_MOD09A1',
    'MODIS/MODIS_061_MOD09GA',
    'MODIS/MODIS_061_MOD09GQ',
    'MODIS/MODIS_061_MOD09Q1',
    'MODIS/MODIS_061_MOD11A1',
    'MODIS/MODIS_061_MOD11A2',
    'MODIS/MODIS_061_MOD13A1',
    'MODIS/MODIS_061_MOD13A2',
    'MODIS/MODIS_061_MOD13Q1',
    'MODIS/MODIS_061_MOD14A1',
    'MODIS/MODIS_061_MOD14A2',
    'MODIS/MODIS_061_MOD15A2H',
    'MODIS/MODIS_061_MOD17A3HGF',
    'MODIS/MODIS_061_MOD21A1D',
    'MODIS/MODIS_061_MOD21A1N',
    'MODIS/MODIS_061_MOD21C1',
    'MODIS/MODIS_061_MOD21C2',
    'MODIS/MODIS_061_MOD21C3',
    'MODIS/MODIS_061_MYD08_M3',
    'MODIS/MODIS_061_MYD09A1',
    'MODIS/MODIS_061_MYD09GA',
    'MODIS/MODIS_061_MYD09GQ',
    'MODIS/MODIS_061_MYD09Q1',
    'MODIS/MODIS_061_MYD11A1',
    'MODIS/MODIS_061_MYD11A2',
    'MODIS/MODIS_061_MYD13A1',
    'MODIS/MODIS_061_MYD13A2',
    'MODIS/MODIS_061_MYD13Q1',
    'MODIS/MODIS_061_MYD14A1',
    'MODIS/MODIS_061_MYD14A2',
    'MODIS/MODIS_061_MYD15A2H',
    'MODIS/MODIS_061_MYD17A3HGF',
    'MODIS/MODIS_061_MYD21A1D',
    'MODIS/MODIS_061_MYD21A1N',
    'MODIS/MODIS_061_MYD21C1',
    'MODIS/MODIS_061_MYD21C2',
    'MODIS/MODIS_061_MYD21C3',
    'MODIS/MODIS_MCD43A1',
    'MODIS/MODIS_MCD43A2',
    'MODIS/MODIS_MCD43A4',
    'MODIS/MODIS_MCD43A4_006_BAI',
    'MODIS/MODIS_MCD43A4_006_EVI',
    'MODIS/MODIS_MCD43A4_006_NDSI',
    'MODIS/MODIS_MCD43A4_006_NDVI',
    'MODIS/MODIS_MCD43A4_006_NDWI',
    'MODIS/MODIS_MCD43A4_BAI',
    'MODIS/MODIS_MCD43A4_EVI',
    'MODIS/MODIS_MCD43A4_NDSI',
    'MODIS/MODIS_MCD43A4_NDVI',
    'MODIS/MODIS_MCD43A4_NDWI',
    'MODIS/MODIS_MOD09A1',
    'MODIS/MODIS_MOD09GA',
    'MODIS/MODIS_MOD09GA_006_BAI',
    'MODIS/MODIS_MOD09GA_006_EVI',
    'MODIS/MODIS_MOD09GA_006_NDSI',
    'MODIS/MODIS_MOD09GA_006_NDVI',
    'MODIS/MODIS_MOD09GA_006_NDWI',
    'MODIS/MODIS_MOD09GA_BAI',
    'MODIS/MODIS_MOD09GA_EVI',
    'MODIS/MODIS_MOD09GA_NDSI',
    'MODIS/MODIS_MOD09GA_NDVI',
    'MODIS/MODIS_MOD09GA_NDWI',
    'MODIS/MODIS_MOD09GQ',
    'MODIS/MODIS_MOD09Q1',
    'MODIS/MODIS_MOD10A1',
    'MODIS/MODIS_MOD11A1',
    'MODIS/MODIS_MOD11A2',
    'MODIS/MODIS_MOD13A1',
    'MODIS/MODIS_MOD13Q1',
    'MODIS/MODIS_MOD44W_MOD44W_005_2000_02_24',
    'MODIS/MODIS_MYD09A1',
    'MODIS/MODIS_MYD09GA',
    'MODIS/MODIS_MYD09GA_006_BAI',
    'MODIS/MODIS_MYD09GA_006_EVI',
    'MODIS/MODIS_MYD09GA_006_NDSI',
    'MODIS/MODIS_MYD09GA_006_NDVI',
    'MODIS/MODIS_MYD09GA_006_NDWI',
    'MODIS/MODIS_MYD09GA_BAI',
    'MODIS/MODIS_MYD09GA_EVI',
    'MODIS/MODIS_MYD09GA_NDSI',
    'MODIS/MODIS_MYD09GA_NDVI',
    'MODIS/MODIS_MYD09GA_NDWI',
    'MODIS/MODIS_MYD09GQ',
    'MODIS/MODIS_MYD09Q1',
    'MODIS/MODIS_MYD10A1',
    'MODIS/MODIS_MYD11A1',
    'MODIS/MODIS_MYD11A2',
    'MODIS/MODIS_MYD13A1',
    'MODIS/MODIS_MYD13Q1',
    'MODIS/MODIS_NTSG_MOD16A2_105',
    'NASA/NASA_ASTER_GED_AG100_003',
    'NASA/NASA_FLDAS_NOAH01_C_GL_M_V001',
    'NASA/NASA_GDDP-CMIP6',
    'NASA/NASA_GEOS-CF_v1_fcst_htf',
    'NASA/NASA_GEOS-CF_v1_rpl_htf',
    'NASA/NASA_GEOS-CF_v1_rpl_tavg1hr',
    'NASA/NASA_GIMMS_3GV0',
    'NASA/NASA_GLDAS_V021_NOAH_G025_T3H',
    'NASA/NASA_GLDAS_V022_CLSM_G025_DA1D',
    'NASA/NASA_GLDAS_V20_NOAH_G025_T3H',
    'NASA/NASA_GPM_L3_IMERG_MONTHLY_V06',
    'NASA/NASA_GPM_L3_IMERG_V06',
    'NASA/NASA_GRACE_MASS_GRIDS_LAND',
    'NASA/NASA_GRACE_MASS_GRIDS_MASCON',
    'NASA/NASA_GRACE_MASS_GRIDS_MASCON_CRI',
    'NASA/NASA_GRACE_MASS_GRIDS_OCEAN',
    'NASA/NASA_GRACE_MASS_GRIDS_OCEAN_EOFR',
    'NASA/NASA_GSFC_MERRA_aer_2',
    'NASA/NASA_GSFC_MERRA_flx_2',
    'NASA/NASA_GSFC_MERRA_lnd_2',
    'NASA/NASA_GSFC_MERRA_rad_2',
    'NASA/NASA_GSFC_MERRA_slv_2',
    'NASA/NASA_JPL_global_forest_canopy_height_2005',
    'NASA/NASA_MEASURES_GFCC_TC_v3',
    'NASA/NASA_NASADEM_HGT_001',
    'NASA/NASA_NEX-DCP30',
    'NASA/NASA_NEX-DCP30_ENSEMBLE_STATS',
    'NASA/NASA_NEX-GDDP',
    'NASA/NASA_NLDAS_FORA0125_H002',
    'NASA/NASA_OCEANDATA_MODIS-Aqua_L3SMI',
    'NASA/NASA_OCEANDATA_MODIS-Terra_L3SMI',
    'NASA/NASA_OCEANDATA_SeaWiFS_L3SMI',
    'NASA/NASA_ORNL_DAYMET_V3',
    'NASA/NASA_ORNL_DAYMET_V4',
    'NASA/NASA_ORNL_biomass_carbon_density_v1',
    'NASA/NASA_SMAP_SPL3SMP_E_005',
    'NASA/NASA_SMAP_SPL3SMP_E_006',
    'NASA/NASA_SMAP_SPL4SMGP_007',
    'NASA_USDA/NASA_USDA_HSL_SMAP10KM_soil_moisture',
    'NASA_USDA/NASA_USDA_HSL_SMAP_soil_moisture',
    'NASA_USDA/NASA_USDA_HSL_soil_moisture',
    'NCEP_RE/NCEP_RE_sea_level_pressure',
    'NCEP_RE/NCEP_RE_surface_temp',
    'NCEP_RE/NCEP_RE_surface_wv',
    'NOAA/NOAA_CDR_ATMOS_NEAR_SURFACE_V2',
    'NOAA/NOAA_CDR_AVHRR_AOT_V3',
    'NOAA/NOAA_CDR_AVHRR_AOT_V4',
    'NOAA/NOAA_CDR_AVHRR_LAI_FAPAR_V4',
    'NOAA/NOAA_CDR_AVHRR_LAI_FAPAR_V5',
    'NOAA/NOAA_CDR_AVHRR_NDVI_V4',
    'NOAA/NOAA_CDR_AVHRR_NDVI_V5',
    'NOAA/NOAA_CDR_AVHRR_SR_V4',
    'NOAA/NOAA_CDR_AVHRR_SR_V5',
    'NOAA/NOAA_CDR_GRIDSAT-B1_V2',
    'NOAA/NOAA_CDR_HEAT_FLUXES_V2',
    'NOAA/NOAA_CDR_OISST_V2',
    'NOAA/NOAA_CDR_OISST_V2_1',
    'NOAA/NOAA_CDR_PATMOSX_V53',
    'NOAA/NOAA_CDR_SST_PATHFINDER_V53',
    'NOAA/NOAA_CDR_SST_WHOI_V2',
    'NOAA/NOAA_CFSR',
    'NOAA/NOAA_CFSV2_FOR6H',
    'NOAA/NOAA_DMSP-OLS_CALIBRATED_LIGHTS_V4',
    'NOAA/NOAA_DMSP-OLS_NIGHTTIME_LIGHTS',
    'NOAA/NOAA_GFS0P25',
    'NOAA/NOAA_GOES_16_FDCC',
    'NOAA/NOAA_GOES_16_MCMIPC',
    'NOAA/NOAA_GOES_16_MCMIPF',
    'NOAA/NOAA_GOES_16_MCMIPM',
    'NOAA/NOAA_GOES_17_FDCC',
    'NOAA/NOAA_GOES_17_FDCF',
    'NOAA/NOAA_GOES_17_MCMIPC',
    'NOAA/NOAA_GOES_17_MCMIPF',
    'NOAA/NOAA_GOES_17_MCMIPM',
    'NOAA/NOAA_GOES_18_FDCC',
    'NOAA/NOAA_GOES_18_FDCF',
    'NOAA/NOAA_GOES_18_MCMIPC',
    'NOAA/NOAA_GOES_18_MCMIPF',
    'NOAA/NOAA_GOES_18_MCMIPM',
    'NOAA/NOAA_NCEP_DOE_RE2_total_cloud_coverage',
    'NOAA/NOAA_NGDC_ETOPO1',
    'NOAA/NOAA_NHC_HURDAT2_atlantic',
    'NOAA/NOAA_NHC_HURDAT2_pacific',
    'NOAA/NOAA_NWS_RTMA',
    'NOAA/NOAA_PERSIANN-CDR',
    'NOAA/NOAA_VIIRS_001_VNP09GA',
    'NOAA/NOAA_VIIRS_001_VNP09H1',
    'NOAA/NOAA_VIIRS_001_VNP13A1',
    'NOAA/NOAA_VIIRS_001_VNP14A1',
    'NOAA/NOAA_VIIRS_001_VNP15A2H',
    'NOAA/NOAA_VIIRS_001_VNP21A1D',
    'NOAA/NOAA_VIIRS_001_VNP21A1N',
    'NOAA/NOAA_VIIRS_001_VNP22Q2',
    'NOAA/NOAA_VIIRS_001_VNP43IA2',
    'NOAA/NOAA_VIIRS_001_VNP46A1',
    'NOAA/NOAA_VIIRS_001_VNP46A2',
    'NOAA/NOAA_VIIRS_001_VNP64A1',
    'NOAA/NOAA_VIIRS_DNB_MONTHLY_V1_VCMCFG',
    'NOAA/NOAA_VIIRS_DNB_MONTHLY_V1_VCMSLCFG',
    'NRCan/NRCan_CDEM',
    'OREGONSTATE/OREGONSTATE_PRISM_AN81d',
    'OREGONSTATE/OREGONSTATE_PRISM_AN81m',
    'OREGONSTATE/OREGONSTATE_PRISM_Norm81m',
    'OREGONSTATE/OREGONSTATE_PRISM_Norm91m',
    'ORTHO/ORTHO_Switzerland_SWISSIMAGE_10cm',
    'OSU/OSU_GIMP_2000_ICE_OCEAN_MASK',
    'OSU/OSU_GIMP_2000_IMAGERY_MOSAIC',
    'OSU/OSU_GIMP_DEM',
    'OSU/OSU_GIMP_ICE_VELOCITY_OPT',
    'OpenLandMap/OpenLandMap_CLM_CLM_LST_MOD11A2-DAYNIGHT_M_v01',
    'OpenLandMap/OpenLandMap_CLM_CLM_LST_MOD11A2-DAY_M_v01',
    'OpenLandMap/OpenLandMap_CLM_CLM_LST_MOD11A2-DAY_SD_v01',
    'OpenLandMap/OpenLandMap_CLM_CLM_PRECIPITATION_SM2RAIN_M_v01',
    'OpenLandMap/OpenLandMap_PNV_PNV_BIOME-TYPE_BIOME00K_C_v01',
    'OpenLandMap/OpenLandMap_PNV_PNV_FAPAR_PROBA-V_D_v01',
    'OpenLandMap/OpenLandMap_SOL_SOL_BULKDENS-FINEEARTH_USDA-4A1H_M_v02',
    'OpenLandMap/OpenLandMap_SOL_SOL_CLAY-WFRACTION_USDA-3A1A1A_M_v02',
    'OpenLandMap/OpenLandMap_SOL_SOL_GRTGROUP_USDA-SOILTAX-HAPLUDALFS_P_v01',
    'OpenLandMap/OpenLandMap_SOL_SOL_GRTGROUP_USDA-SOILTAX_C_v01',
    'OpenLandMap/OpenLandMap_SOL_SOL_ORGANIC-CARBON_USDA-6A1C_M_v02',
    'OpenLandMap/OpenLandMap_SOL_SOL_PH-H2O_USDA-4C1A2A_M_v02',
    'OpenLandMap/OpenLandMap_SOL_SOL_SAND-WFRACTION_USDA-3A1A1A_M_v02',
    'OpenLandMap/OpenLandMap_SOL_SOL_TEXTURE-CLASS_USDA-TT_M_v02',
    'OpenLandMap/OpenLandMap_SOL_SOL_WATERCONTENT-33KPA_USDA-4B1C_M_v01',
    'Oxford/Oxford_MAP_EVI_5km_Monthly',
    'Oxford/Oxford_MAP_IGBP_Fractional_Landcover_5km_Annual',
    'Oxford/Oxford_MAP_LST_Day_5km_Monthly',
    'Oxford/Oxford_MAP_LST_Night_5km_Monthly',
    'Oxford/Oxford_MAP_TCB_5km_Monthly',
    'Oxford/Oxford_MAP_TCW_5km_Monthly',
    'Oxford/Oxford_MAP_accessibility_to_cities_2015_v1_0',
    'Oxford/Oxford_MAP_accessibility_to_healthcare_2019',
    'Oxford/Oxford_MAP_friction_surface_2015_v1_0',
    'Oxford/Oxford_MAP_friction_surface_2019',
    'RESOLVE/RESOLVE_ECOREGIONS_2017',
    'SKYSAT/SKYSAT_GEN-A_PUBLIC_ORTHO_MULTISPECTRAL',
    'SKYSAT/SKYSAT_GEN-A_PUBLIC_ORTHO_RGB',
    'SNU/SNU_ESL_BESS_Rad_v1',
    'Spain/Spain_PNOA_PNOA10',
    'Switzerland/Switzerland_SWISSIMAGE_orthos_10cm',
    'TERN/TERN_AET_CMRSET_LANDSAT_V2_1',
    'TERN/TERN_AET_CMRSET_LANDSAT_V2_2',
    'TIGER/TIGER_2010_BG',
    'TIGER/TIGER_2010_Blocks',
    'TIGER/TIGER_2010_Tracts_DP1',
    'TIGER/TIGER_2010_ZCTA5',
    'TIGER/TIGER_2016_Counties',
    'TIGER/TIGER_2016_Roads',
    'TIGER/TIGER_2016_States',
    'TIGER/TIGER_2018_Counties',
    'TIGER/TIGER_2018_States',
    'TIGER/TIGER_2020_BG',
    'TIGER/TIGER_2020_TABBLOCK20',
    'TIGER/TIGER_2020_TRACT',
    'TOMS/TOMS_MERGED',
    'TRMM/TRMM_3B42',
    'TRMM/TRMM_3B43V7',
    'TUBerlin/TUBerlin_BigEarthNet_v1',
    'Tsinghua/Tsinghua_DESS_ChinaTerraceMap_v1',
    'Tsinghua/Tsinghua_FROM-GLC_GAIA_v10',
    'UCSB-CHG/UCSB-CHG_CHIRPS_DAILY',
    'UCSB-CHG/UCSB-CHG_CHIRPS_PENTAD',
    'UMD/UMD_GLAD_PRIMARY_HUMID_TROPICAL_FORESTS_v1',
    'UMD/UMD_hansen_global_forest_change_2013',
    'UMD/UMD_hansen_global_forest_change_2014',
    'UMD/UMD_hansen_global_forest_change_2015',
    'UMD/UMD_hansen_global_forest_change_2015_v1_3',
    'UMD/UMD_hansen_global_forest_change_2016_v1_4',
    'UMD/UMD_hansen_global_forest_change_2017_v1_5',
    'UMD/UMD_hansen_global_forest_change_2018_v1_6',
    'UMD/UMD_hansen_global_forest_change_2019_v1_7',
    'UMD/UMD_hansen_global_forest_change_2020_v1_8',
    'UMD/UMD_hansen_global_forest_change_2021_v1_9',
    'UMD/UMD_hansen_global_forest_change_2022_v1_10',
    'UMD/UMD_hansen_global_forest_change_2023_v1_11',
    'UMN/UMN_PGC_ArcticDEM_V2_2m',
    'UMN/UMN_PGC_ArcticDEM_V2_5m',
    'UMN/UMN_PGC_ArcticDEM_V3_2m',
    'UMN/UMN_PGC_ArcticDEM_V3_2m_mosaic',
    'UMN/UMN_PGC_REMA_V1_1_8m',
    'UMN/UMN_PGC_REMA_V1_2m',
    'UMN/UMN_PGC_REMA_V1_8m',
    'UMT/UMT_Climate_IrrMapper_RF_v1_1',
    'UMT/UMT_NTSG_v2_LANDSAT_GPP',
    'UMT/UMT_NTSG_v2_LANDSAT_NPP',
    'UMT/UMT_NTSG_v2_MODIS_GPP',
    'UMT/UMT_NTSG_v2_MODIS_NPP',
    'UQ/UQ_murray_Intertidal_v1_1_data_mask',
    'UQ/UQ_murray_Intertidal_v1_1_global_intertidal',
    'UQ/UQ_murray_Intertidal_v1_1_qa_pixel_count',
    'USDA/USDA_NAIP_DOQQ',
    'USDA/USDA_NASS_CDL',
    'USDOS/USDOS_LSIB_2013',
    'USDOS/USDOS_LSIB_2017',
    'USDOS/USDOS_LSIB_SIMPLE_2017',
    'USFS/USFS_GTAC_MTBS_annual_burn_severity_mosaics_v1',
    'USFS/USFS_GTAC_MTBS_burned_area_boundaries_v1',
    'USGS/USGS_3DEP_10m',
    'USGS/USGS_3DEP_10m_metadata',
    'USGS/USGS_3DEP_1m',
    'USGS/USGS_GAP_AK_2001',
    'USGS/USGS_GAP_CONUS_2011',
    'USGS/USGS_GAP_HI_2001',
    'USGS/USGS_GAP_PAD-US_v20_designation',
    'USGS/USGS_GAP_PAD-US_v20_easement',
    'USGS/USGS_GAP_PAD-US_v20_fee',
    'USGS/USGS_GAP_PAD-US_v20_proclamation',
    'USGS/USGS_GAP_PR_2001',
    'USGS/USGS_GFSAD1000_V0',
    'USGS/USGS_GFSAD1000_V1',
    'USGS/USGS_GMTED2010',
    'USGS/USGS_GTOPO30',
    'USGS/USGS_LIMA_MOSAIC',
    'USGS/USGS_LIMA_SR',
    'USGS/USGS_NED',
    'USGS/USGS_NLCD',
    'USGS/USGS_NLCD_RELEASES_2016_REL',
    'USGS/USGS_NLCD_RELEASES_2019_REL_NLCD',
    'USGS/USGS_NLCD_RELEASES_2019_REL_RCMAP_V4_COVER',
    'USGS/USGS_SRTMGL1_003',
    'USGS/USGS_WBD_2017_HUC02',
    'USGS/USGS_WBD_2017_HUC04',
    'USGS/USGS_WBD_2017_HUC06',
    'USGS/USGS_WBD_2017_HUC08',
    'USGS/USGS_WBD_2017_HUC10',
    'USGS/USGS_WBD_2017_HUC12',
    'UTOKYO/UTOKYO_WTLAB_KBDI_v1',
    'VITO/VITO_PROBAV_C1_S1_TOC_100M',
    'VITO/VITO_PROBAV_C1_S1_TOC_333M',
    'VITO/VITO_PROBAV_S1_TOC_100M',
    'VITO/VITO_PROBAV_S1_TOC_333M',
    'WCMC/WCMC_WDPA_current_points',
    'WCMC/WCMC_WDPA_current_polygons',
    'WCMC/WCMC_biomass_carbon_density_v1_0',
    'WHBU/WHBU_NBAR_1YEAR',
    'WHBU/WHBU_NBAR_2YEAR',
    'WHBU/WHBU_NBAR_3YEAR',
    'WHRC/WHRC_biomass_tropical',
    'WORLDCLIM/WORLDCLIM_V1_BIO',
    'WORLDCLIM/WORLDCLIM_V1_MONTHLY',
    'WRI/WRI_GFW_FORMA_alerts',
    'WRI/WRI_GFW_FORMA_raw_output_firms',
    'WRI/WRI_GFW_FORMA_raw_output_ndvi',
    'WRI/WRI_GFW_FORMA_thresholds',
    'WRI/WRI_GFW_FORMA_vegetation_tstats',
    'WRI/WRI_GPPD_power_plants',
    'WWF/WWF_HydroATLAS_v1_Basins_level03',
    'WWF/WWF_HydroATLAS_v1_Basins_level04',
    'WWF/WWF_HydroATLAS_v1_Basins_level05',
    'WWF/WWF_HydroATLAS_v1_Basins_level06',
    'WWF/WWF_HydroATLAS_v1_Basins_level07',
    'WWF/WWF_HydroATLAS_v1_Basins_level08',
    'WWF/WWF_HydroATLAS_v1_Basins_level09',
    'WWF/WWF_HydroATLAS_v1_Basins_level10',
    'WWF/WWF_HydroATLAS_v1_Basins_level11',
    'WWF/WWF_HydroATLAS_v1_Basins_level12',
    'WWF/WWF_HydroSHEDS_03CONDEM',
    'WWF/WWF_HydroSHEDS_03DIR',
    'WWF/WWF_HydroSHEDS_03VFDEM',
    'WWF/WWF_HydroSHEDS_15ACC',
    'WWF/WWF_HydroSHEDS_15CONDEM',
    'WWF/WWF_HydroSHEDS_15DIR',
    'WWF/WWF_HydroSHEDS_30ACC',
    'WWF/WWF_HydroSHEDS_30CONDEM',
    'WWF/WWF_HydroSHEDS_30DIR',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_1',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_10',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_11',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_12',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_2',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_3',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_4',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_5',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_6',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_7',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_8',
    'WWF/WWF_HydroSHEDS_v1_Basins_hybas_9',
    'WWF/WWF_HydroSHEDS_v1_FreeFlowingRivers',
    'WorldPop/WorldPop_GP_100m_pop',
    'WorldPop/WorldPop_GP_100m_pop_age_sex',
    'WorldPop/WorldPop_GP_100m_pop_age_sex_cons_unadj',
    'WorldPop/WorldPop_POP',
    'YALE/YALE_YCEO_UHI_Summer_UHI_yearly_pixel_v4',
    'YALE/YALE_YCEO_UHI_UHI_all_averaged_v4',
    'YALE/YALE_YCEO_UHI_UHI_monthly_averaged_v4',
    'YALE/YALE_YCEO_UHI_UHI_yearly_averaged_v4',
    'YALE/YALE_YCEO_UHI_UHI_yearly_pixel_v4',
    'YALE/YALE_YCEO_UHI_Winter_UHI_yearly_pixel_v4',
    'planet-nicfi/projects_planet-nicfi_assets_basemaps_africa',
    'planet-nicfi/projects_planet-nicfi_assets_basemaps_americas',
    'planet-nicfi/projects_planet-nicfi_assets_basemaps_asia',
]

_PREVIEW_EXCEPTIONS = frozenset({
    item + '_preview.js' for item in _PREVIEW_EXCEPTIONS_LIST})


_GEE_SKIP_FEATUREVIEW_GENERATION = 'gee:skip_featureview_generation'


def load(examples_root: pathlib.Path) -> set[str]:
  return {str(path.relative_to(examples_root))
          for path in examples_root.rglob('*.js')
          if not path.name.endswith('_preview.js')}


def load_previews(examples_root: pathlib.Path) -> set[str]:
  return {str(path.relative_to(examples_root))
          for path in examples_root.rglob('*.js')
          if path.name.endswith('_preview.js')}


class Check(stac.NodeCheck):
  """Checks for examples."""
  name = 'examples'
  scripts: set[str] = set()
  preview_scripts: set[str] = set()

  @classmethod
  def run(cls, node: stac.Node) -> Iterator[stac.Issue]:
    if node.type == stac.StacType.CATALOG: return
    if node.id.startswith('TEMPLATE'): return

    # CCDC is not planned to be made public so far, so it has
    # no examples.
    if node.id == 'GOOGLE/GLOBAL_CCDC/V1': return

    if not cls.scripts:
      cls.scripts = load(stac.examples_root())

    if not cls.preview_scripts:
      cls.preview_scripts = load_previews(stac.previews_root())

    stem = node.path.stem
    name = stem + '.js'
    subdir = (node.id.split('/')[1] if node.id.startswith('projects/')
              else node.id.split('/')[0])
    basename = subdir + '/' + node.id.replace('/', '_')
    filename = basename + '.js'
    preview_filename = basename + '_preview.js'
    featureview_filename = basename + '_FeatureView.js'

    if filename not in cls.scripts and name not in _EXCEPTIONS:
      yield cls.new_issue(node, f'Missing script: {filename}')

    if preview_filename not in cls.preview_scripts:
      if preview_filename not in _PREVIEW_EXCEPTIONS:
        yield cls.new_issue(node, f'Missing preview script: {preview_filename}')
    elif preview_filename in _PREVIEW_EXCEPTIONS:
      yield cls.new_issue(
          node,
          f'Remove preview script from _PREVIEW_EXCEPTIONS: {preview_filename}')

    if node.gee_type == stac.GeeType.TABLE:
      if (featureview_filename not in cls.scripts and
          _GEE_SKIP_FEATUREVIEW_GENERATION not in node.stac and
          str(featureview_filename) not in _FEATURE_VIEW_EXCEPTIONS):
        yield cls.new_issue(
            node, f'Missing FeatureView script: {featureview_filename}')
    else:
      if featureview_filename in cls.scripts:
        yield cls.new_issue(
            node,
            'Only a table can have a FeatureView script: ' +
            str(featureview_filename))
