local tempo_no2_l3_qa = import 'templates/NASA_TEMPO_NO2.libsonnet';

local id = "NASA/TEMPO/NO2_L3_QA";
local qa_title = ' (QA filtered)';
local qa_description = |||

  The QA Filtered TEMPO NO2 L3 dataset is a quality-controlled version of
  the original data. It is generated by removing data points with high cloud
  cover (>50%), extreme solar zenith angle (>80 degrees), and
  main data quality (flag > 0).
|||;
local quality_flag_desc = |||
  Main data quality flag which is always 0, indicating good quality data.
|||;
local effective_cloud_fraction_desc = |||
  Data is filtered to include only observations with effective cloud fraction
  less than or equal to 50%.
|||;
local solar_zenith_angle_desc = |||
  Data is filtered to include only observations with solar zenith angle
  less than or equal to 80 degrees.
|||;

tempo_no2_l3_qa.nasa_tempo_no2_collection({
  id:id,
  qa_title: qa_title,
  qa_description: qa_description,
  quality_flag_desc: quality_flag_desc,
  effective_cloud_fraction_desc: effective_cloud_fraction_desc,
  solar_zenith_angle_desc: solar_zenith_angle_desc
})
