local id = 'NASA/NISAR/L3_SME2';
local subdir = 'NASA';
local version = 'V1';
local doi = '10.5067/NIL3SME2-P1';

local ee_const = import 'earthengine_const.libsonnet';
local ee = import 'earthengine.libsonnet';
local spdx = import 'spdx.libsonnet';
local units = import 'units.libsonnet';

local license = spdx.proprietary;

local basename = std.strReplace(id, '/', '_');
local self_ee_catalog_url = ee_const.ee_catalog_url + basename;

{
  stac_version: ee_const.stac_version,
  type: ee_const.stac_type.collection,
  stac_extensions: [
    ee_const.ext_eo,
    ee_const.ext_sci,
    ee_const.ext_ver,
  ],
  id: id,
  title: 'NISAR L3 Soil Moisture (SME2) 200m ' + version,
  version: version,
  'gee:status': 'beta',
  'gee:type': ee_const.gee_type.image_collection,
  description: |||
    The NASA-ISRO Synthetic Aperture Radar (NISAR) Level 3 Soil Moisture
    (SME2) dataset provides estimated volumetric soil moisture (0-5 cm depth)
    at 200 m spatial resolution on the global cylindrical equal-area
    EASE-Grid 2.0 (EPSG:6933).

    NISAR is a joint Earth-observing mission developed by NASA and the Indian
    Space Research Organisation (ISRO). The SME2 product is generated by the
    Science Data System (SDS) at NASA JPL and distributed by the Alaska
    Satellite Facility (ASF) DAAC. Soil moisture estimates are derived from
    NISAR L2 geocoded polarimetric covariance (GCOV) radar backscatter
    measurements acquired in L-band (Frequency A: 1.239 GHz, Frequency B:
    1.2935 GHz) combined with ancillary data (such as land cover, surface
    temperature, and waterbody fraction).

    In addition to soil moisture estimates and retrieval uncertainty, each
    granule contains pixel-level quality flags, ancillary land cover and water
    fraction, local incidence angle, and dynamic calibrated linear radar
    backscatter coefficients (`sigma0`) for available polarization channels
    across Frequency A and B. The availability of individual `sigma0` bands
    varies by the polarizations acquired for each granule. The available
    polarizations for each granule are provided in the
    `transmitterReceiverPolarizationA`
    and `transmitterReceiverPolarizationB` metadata properties.

    ### Product Maturity (`status`) and Duplicate Granules

    Each asset has a `status` property giving its Earth Engine ingestion
    track, which corresponds to the NASA product quality designation:
    `'provisional'` for Provisional, and `'permanent'` for the future
    Validated release. Per
    [ASF's SME2 known issues](https://nisar-docs.asf.alaska.edu/provisional-known-issues/#provisional-known-issues-sme2),
    Provisional SME2 products are partially validated and not yet fully
    calibrated because long time series of Provisional GCOV inputs are not yet
    available.

    Every granule version is ingested as a distinct asset; no asset is
    replaced or removed when a newer version arrives. Ingesting a
    higher-maturity version of a granule does not remove the lower-maturity
    version, and a granule regenerated by the provider (with a higher
    `crid` or `counter`) is ingested alongside the previous version. The
    collection may therefore contain several assets for the same acquisition,
    and users must select among them explicitly. Filter on `status` (e.g.,
    `ee.Filter.eq('status', 'provisional')`) to select a single maturity
    track. Within a track, the most recent version of a granule is the one
    with the highest `crid`, then the highest `counter`. Because `mosaic()`
    and map display draw the last image on top, sort the collection by
    version (ascending) so that the most recent version is displayed where
    granules overlap.

    ### Granule Naming and Composite Release ID (`crid`)

    Granule names follow the NISAR L-SAR product file naming convention
    (JPL D-102255), and the fields of the name are provided as asset
    properties. The Composite Release Identifier (`crid`, formatted `EMMmmp`)
    gives the processing environment (`E`, e.g., `P` for Production or `R` for
    Reprocessing), followed by the major (`MM`), minor (`mm`), and patch (`p`)
    release of the processing software. For example, `P05023` denotes
    Production major release 05, minor release 02, patch 3. CRID values
    increase monotonically. CRIDs do not encode product maturity; use `status`
    for that.

    Granules whose polarization mode contains `XX` for either frequency (an
    off-nominal set of polarizations, e.g., due to downlink failures) are not
    ingested.

    ### Documentation

    * [NISAR SME2 Product Documentation](https://nisar-docs.asf.alaska.edu/sme2/)
    * [NISAR L3 SME2 Product Specification (JPL D-107677 Rev C)](https://nisar.asf.earthdatacloud.nasa.gov/NISAR-SAMPLE-DATA/DOCS/NISAR_D-107677_RevC_NASA_SDS_Product_Specification_L3_SME2_Nov8_2024_w-sigs.pdf)
    * [NISAR Naming Conventions Guide](https://nisar-docs.asf.alaska.edu/naming-conventions/)
    * [NISAR L-SAR Product File Naming Conventions (JPL D-102255 Rev C)](https://nisar.asf.earthdatacloud.nasa.gov/NISAR-SAMPLE-DATA/DOCS/NISAR_D-102255C_SDS_L-SAR_File_Naming_Convention-20251019_clean_w_esigs.pdf)
    * [NASA Earthdata Dataset Landing Page](https://doi.org/%s)
  ||| % doi,
  license: license.id,
  links: ee.standardLinks(subdir, id) + [
    {
      rel: ee_const.rel.cite_as,
      href: 'https://doi.org/' + doi,
    },
  ],
  'gee:categories': ['soil'],
  keywords: [
    'backscatter',
    'jpl',
    'nasa',
    'radar',
    'sar',
    'soil_moisture',
    'surface',
  ],
  providers: [
    ee.producer_provider('NASA JPL / ASF DAAC', 'https://doi.org/' + doi),
    ee.host_provider(self_ee_catalog_url),
  ],
  'gee:provider_ids': [
    'C2854344945-ASF',
  ],
  extent: ee.extent_global('2025-11-24T00:00:00Z', null),
  summaries: {
    gsd: [
      200.18,
    ],
    platform: [
      'NISAR',
    ],
    instruments: [
      'L-SAR',
    ],
    'eo:bands': [
      {
        name: 'soilMoisture',
        description: 'Estimated volumetric soil moisture (0-5 cm depth)',
        'gee:units': units.volume_fraction,
      },
      {
        name: 'uncertainty',
        description: 'Soil moisture retrieval uncertainty standard deviation',
        'gee:units': units.volume_fraction,
      },
      {
        name: 'qualityFlag',
        description: |||
          Pixel-level retrieval quality flag bitmask. Bit 0 set to 0 indicates
          a recommended retrieval
        |||,
        'gee:bitmask': {
          total_bit_count: 8,
          bitmask_parts: [
            {
              first_bit: 0,
              bit_count: 1,
              description: 'Retrieval recommended flag',
              values: [
                {value: 0, description: 'Recommended'},
                {value: 1, description: 'Not recommended'},
              ],
            },
            {
              first_bit: 1,
              bit_count: 1,
              description: 'Retrieval attempted flag',
              values: [
                {value: 0, description: 'Attempted'},
                {value: 1, description: 'Not attempted'},
              ],
            },
            {
              first_bit: 2,
              bit_count: 1,
              description: 'Retrieval success flag',
              values: [
                {value: 0, description: 'Success'},
                {value: 1, description: 'Failure'},
              ],
            },
            {
              first_bit: 3,
              bit_count: 1,
              description: 'Soil moisture threshold check (0.02 - 0.60 m^3/m^3)',
              values: [
                {value: 0, description: 'Within thresholds'},
                {value: 1, description: 'Outside thresholds'},
              ],
            },
            {
              first_bit: 4,
              bit_count: 1,
              description: 'NISAR sigma0_HH anomaly flag',
              values: [
                {value: 0, description: 'Nominal'},
                {value: 1, description: 'Anomaly'},
              ],
            },
            {
              first_bit: 5,
              bit_count: 1,
              description: 'NISAR sigma0_HV anomaly flag',
              values: [
                {value: 0, description: 'Nominal'},
                {value: 1, description: 'Anomaly'},
              ],
            },
            {
              first_bit: 6,
              bit_count: 1,
              description: 'NISAR sigma0_VV anomaly flag',
              values: [
                {value: 0, description: 'Nominal'},
                {value: 1, description: 'Anomaly'},
              ],
            },
            {
              first_bit: 7,
              bit_count: 1,
              description: 'NISAR sigma0_VH anomaly flag',
              values: [
                {value: 0, description: 'Nominal'},
                {value: 1, description: 'Anomaly'},
              ],
            },
          ],
        },
      },
      {
        name: 'landCover',
        description: 'Ancillary land cover class',
        'gee:classes': [
          {value: 1, color: '006400', description: 'Tree cover'},
          {value: 2, color: 'ffbb22', description: 'Shrublands'},
          {value: 3, color: 'ffff4c', description: 'Grassland'},
          {value: 4, color: 'f096ff', description: 'Cropland'},
          {value: 5, color: 'fa0000', description: 'Built-up'},
          {value: 6, color: 'b4b4b4', description: 'Bare/sparse vegetation'},
          {value: 7, color: 'f0f0f0', description: 'Snow and ice'},
          {value: 8, color: '0064c8', description: 'Permanent water bodies'},
          {value: 9, color: '0096a0', description: 'Herbaceous wetland'},
          {value: 10, color: '00cf75', description: 'Mangroves'},
          {value: 11, color: 'fae6a0', description: 'Moss and lichen'},
        ],
      },
      {
        name: 'waterFraction',
        description: 'Fraction of the grid cell covered by water',
        'gee:units': units.area_fraction,
      },
      {
        name: 'incidenceAngle',
        description: 'Local radar incidence angle',
        'gee:units': units.degree,
      },
      {
        name: 'sigma0HH_A',
        description:
          'Calibrated radar backscatter (sigma0) for HH polarization at Frequency A (1.239 GHz). ' +
          'Availability varies by the available polarizations for each granule.',
        'gee:units': units.dimensionless,
      },
      {
        name: 'sigma0HV_A',
        description:
          'Calibrated radar backscatter (sigma0) for HV polarization at Frequency A (1.239 GHz). ' +
          'Availability varies by the available polarizations for each granule.',
        'gee:units': units.dimensionless,
      },
      {
        name: 'sigma0VV_A',
        description:
          'Calibrated radar backscatter (sigma0) for VV polarization at Frequency A (1.239 GHz). ' +
          'Availability varies by the available polarizations for each granule.',
        'gee:units': units.dimensionless,
      },
      {
        name: 'sigma0VH_A',
        description:
          'Calibrated radar backscatter (sigma0) for VH polarization at Frequency A (1.239 GHz). ' +
          'Availability varies by the available polarizations for each granule.',
        'gee:units': units.dimensionless,
      },
      {
        name: 'sigma0HH_B',
        description:
          'Calibrated radar backscatter (sigma0) for HH polarization at Frequency B (1.2935 GHz). ' +
          'Availability varies by the available polarizations for each granule.',
        'gee:units': units.dimensionless,
      },
      {
        name: 'sigma0HV_B',
        description:
          'Calibrated radar backscatter (sigma0) for HV polarization at Frequency B (1.2935 GHz). ' +
          'Availability varies by the available polarizations for each granule.',
        'gee:units': units.dimensionless,
      },
      {
        name: 'sigma0VV_B',
        description:
          'Calibrated radar backscatter (sigma0) for VV polarization at Frequency B (1.2935 GHz). ' +
          'Availability varies by the available polarizations for each granule.',
        'gee:units': units.dimensionless,
      },
      {
        name: 'sigma0VH_B',
        description:
          'Calibrated radar backscatter (sigma0) for VH polarization at Frequency B (1.2935 GHz). ' +
          'Availability varies by the available polarizations for each granule.',
        'gee:units': units.dimensionless,
      },
    ],
    'gee:schema': [
      {
        name: 'accuracy',
        description: |||
          Accuracy (fidelity) of the orbit ephemeris and radar pointing data
          used in processing, whichever is lower ('P' for Precise, 'M' for
          Medium, 'N' for Near real-time, 'F' for Forecast, 'X' for Special
          request)
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'bandwidthMode',
        description: |||
          Bandwidth mode code: one 2-digit code each for the primary
          (Frequency A) and secondary (Frequency B) bands, either the bandwidth
          in MHz ('40', '20', '77', or '05') or '00' if the band is absent
          (e.g., '4005', '2005', '0505', '0005')
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'counter',
        description: |||
          Product counter (1-999). Incremented when the same granule is
          regenerated under the same CRID; reset to 1 for a new CRID
        |||,
        type: ee_const.var_type.int,
      },
      {
        name: 'coverage',
        description: |||
          Frame coverage indicator ('F' for Full, if at least 75% of the frame
          is covered; 'P' for Partial)
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'crid',
        description: |||
          Composite Release Identifier, formatted EMMmmp: processing
          environment, then major, minor, and patch release of the processing
          software (e.g., 'P05023')
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'cycleNumber',
        description: 'NISAR orbit cycle number (12-day repeat cycle)',
        type: ee_const.var_type.int,
      },
      {
        name: 'frameNumber',
        description: 'Track frame number along the orbit (1-176)',
        type: ee_const.var_type.int,
      },
      {
        name: 'passDirection',
        description: "Orbit pass direction ('A' for Ascending, 'D' for Descending)",
        type: ee_const.var_type.string,
      },
      {
        name: 'polarizationMode',
        description: |||
          Polarization mode code across Frequency A and B (e.g., DHDH, SVSH,
          NASV, QPDH)
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'processingCenter',
        description: |||
          Science Data System processing location ('J' for JPL, 'I' for ISRO)
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'relativeOrbitTrack',
        description: 'Relative orbit track number within a cycle (1-173)',
        type: ee_const.var_type.int,
      },
      {
        name: 'sourceMode',
        description: |||
          Source of data for the product ('A' for Acquired single mode, 'M' for
          Mixed mode)
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'status',
        description: |||
          Earth Engine ingestion track, corresponding to the NASA product
          quality designation ('provisional' for Provisional, 'permanent' for
          Validated)
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'transmitterReceiverPolarizationA',
        description: 'List of polarizations available for Frequency A',
        type: ee_const.var_type.string_list,
      },
      {
        name: 'transmitterReceiverPolarizationB',
        description: 'List of polarizations available for Frequency B',
        type: ee_const.var_type.string_list,
      },
    ],
    'gee:visualizations': [
      {
        display_name: 'Soil Moisture',
        lookat: {
          lat: 35.5,
          lon: 140.0,
          zoom: 6,
        },
        image_visualization: {
          band_vis: {
            min: [0.0],
            max: [0.5],
            bands: ['soilMoisture'],
            palette: [
              '0300ff',
              '418504',
              'efff07',
              'ff0303',
            ],
          },
        },
      },
    ],
  },
  'sci:doi': doi,
  'sci:citation': |||
    NASA/JPL/ASF. (2025). NISAR L3 Soil Moisture (SME2) Version 1 [Data set].
    NASA Alaska Satellite Facility Distributed Active Archive Center.
    [doi:%s](https://doi.org/%s)
  ||| % [doi, doi],
  'gee:terms_of_use': |||
    This dataset is in the public domain and is available
    without restriction on use and distribution. See [NASA's
    Earth Science Data & Information Policy](https://www.earthdata.nasa.gov/engage/open-data-services-and-software/data-and-information-policy)
    for additional information.
  |||,
}
