local id = 'projects/gcp-public-data-weathernext/assets/weathernext_3_0_0_0p05deg';
local subdir = 'gcp-public-data-weathernext';

local ee_const = import 'earthengine_const.libsonnet';
local ee = import 'earthengine.libsonnet';
local spdx = import 'spdx.libsonnet';
local units = import 'units.libsonnet';

local basename = std.strReplace(id, '/', '_');
local base_filename = basename + '.json';
local self_ee_catalog_url = ee_const.ee_catalog_url + basename;
local catalog_subdir_url = ee_const.catalog_base + subdir + '/';
local parent_url = catalog_subdir_url + 'catalog.json';
local self_url = catalog_subdir_url + base_filename;

local license = spdx.proprietary;

{
  'gee:user_uploaded': true,
  stac_version: ee_const.stac_version,
  type: ee_const.stac_type.collection,
  stac_extensions: [
    ee_const.ext_eo,
    ee_const.ext_sci,
  ],
  id: id,
  title: 'WeatherNext 3 (0.05&deg;)',
  'gee:type': ee_const.gee_type.image_collection,
  description: |||
    WeatherNext 3 (0.05&deg;) dataset is an experimental dataset of global
    medium-range **ensemble weather forecasts** by Google DeepMind and Google
    Research, produced by an operational version of the model described in:
    [WeatherNext 3: Increasing resolution and performance of global weather
    models with raw observations](https://storage.googleapis.com/deepmind-media/papers/weathernext_3.pdf).

    **Data Access**

    To request access to the experimental dataset, please submit the
    [WeatherNext Data Request form](https://docs.google.com/forms/d/e/1FAIpQLSeCf1JY8G78UDWzbm0ly9kJxfSjUIJT5WyMR_HiNqCm-IHIBg/viewform).

    **Model Highlights**

    *   **High resolution & rapid refresh**: 0.05&deg; (~5 km) global spatial
        resolution for some variables, native 1-hour forecast timesteps,
        hourly initialization, and lead times extending up to 15 days.
    *   **Real-time observational grounding**: Integrates global geostationary
        satellite mosaics directly into model inputs, enabling rapid assimilation of
        current weather patterns.
    *   **Calibrated surface variables**: Calibrated against ground weather
        station networks for surface temperature/dewpoint and satellite
        observations (IMERG) for precipitation.
    *   **Solar & energy-focused fields**: Predicts multi-layer cloud cover and
        downward, direct, and clear-sky solar irradiance to support renewable energy
        and environmental modeling.

    This Earth Engine collection provides ensemble summary statistics (mean and spread)
    derived from the operational WeatherNext 3 ensemble, optimized for geospatial analysis.
    It includes station head forecasts for 2m temperature and dew point across six precomputed
    statistical metrics -- specifically mean, p10, p25, p50, p75, and p90 (total of 12 bands).

    Forecast Horizon:

    *   **6-hour inits (00, 06, 12, 18 UTC)**: with a 360-hour (15-day) horizon.
    *   **Interim 1-hour inits (01-05, 07-11, 13-17, 19-23 UTC)**: with a 48-hour horizon.

    Learn more about WeatherNext [here](https://developers.google.com/weathernext/guides/models).
    For access to the full ensemble dataset and atmospheric data, go to our
    [Google Cloud Storage bucket](https://developers.google.com/weathernext/guides/gcs).

    **Data Availability**

    The experimental dataset includes both real-time and historic data:

    *   **Real-Time Experimental Data**: Any data relating to a time more recent than 1 hour ago.
    *   **Historic Experimental Data**: Any data relating to a time 1 hour ago or older.

    **More information**

    *   **Model guide and specifications**: For more details on WeatherNext,
        including technical details and specifications, visit the
        [WeatherNext Models Guide](https://developers.google.com/weathernext/guides/models)
        and the [WeatherNext Developer Guide](https://developers.google.com/weathernext).
    *   **Research paper**: More information on the underlying research model is
        available [here](https://storage.googleapis.com/deepmind-media/papers/weathernext_3.pdf). Please note that
        the accuracy of this operational model may not directly correspond to the
        accuracy reported for the research model, and that additional variables
        may be included in this forecast dataset.
    *   **Contact**: For questions or usage outside permitted terms,
        contact weathernext@google.com. Any information collected via email will
        be used in accordance with [Google's Privacy Policy](https://policies.google.com/privacy).

    **Dissemination Schedule**

    For forecast release timing, expected delivery windows, and latency across platforms,
    see the [WeatherNext Dissemination Schedule](https://developers.google.com/weathernext/guides/dissemination).

    **Acknowledgements**

    This experimental dataset was generated by a model using data and products of
    the European Centre for Medium-Range Weather Forecasts (ECMWF), as well as
    additional third-party providers.  For a full list of attribution and acknowledgements,
    please see our [acknowledgements page](https://storage.googleapis.com/weathernext-public/weathernext-3-attributions-acknowledgements.pdf).
  |||,
  license: license.id,
  links: ee.standardLinks(subdir, id),
  'gee:categories': ['climate'],
  keywords: [
    'weather',
    'weathernext',
    'forecast',
    'temperature',
    'precipitation',
    'wind',
    'humidity',
    'flood',
  ],
  providers: [
    ee.producer_provider('Google', 'https://developers.google.com/weathernext'),
    ee.host_provider(self_ee_catalog_url),
  ],
  extent: ee.extent_global('2026-01-01T00:00:00Z', null),
  summaries: {
    gsd: [5566],
    'gee:schema': [
      {
        name: 'start_time',
        description: |||
          The initialization time of the forecast. This is the same for all
          forecast hours within a single model run.
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'end_time',
        description: |||
          The valid time for this specific forecast. Calculated as
          start_time + forecast_hour.
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'forecast_hour',
        description: |||
          The forecast lead time in hours. Represents the number of hours from
          the start_time (1 to 360 for 6-hourly inits, 1 to 48 for interim
          hourly inits).
        |||,
        type: ee_const.var_type.int,
      },
      {
        name: 'ingestion_time_utc',
        description: |||
          The time when this forecast data became available in Earth Engine.
        |||,
        type: ee_const.var_type.double,
      },
      {
        name: 'B_',
        description: |||
          The band names in the order, starting from B0 to B11.
        |||,
        type: ee_const.var_type.string,
      },
    ],
    'eo:bands': [
      {
        name: 'station_head_dewpoint_temperature_2m_mean',
        description: |||
          Mean of station head 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'station_head_dewpoint_temperature_2m_p10',
        description: |||
          10th percentile of station head 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'station_head_dewpoint_temperature_2m_p25',
        description: |||
          25th percentile of station head 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'station_head_dewpoint_temperature_2m_p50',
        description: |||
          Median of station head 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'station_head_dewpoint_temperature_2m_p75',
        description: |||
          75th percentile of station head 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'station_head_dewpoint_temperature_2m_p90',
        description: |||
          90th percentile of station head 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'station_head_temperature_2m_mean',
        description: |||
          Mean of station head 2 metre temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'station_head_temperature_2m_p10',
        description: |||
          10th percentile of station head 2 metre temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'station_head_temperature_2m_p25',
        description: |||
          25th percentile of station head 2 metre temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'station_head_temperature_2m_p50',
        description: |||
          Median of station head 2 metre temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'station_head_temperature_2m_p75',
        description: |||
          75th percentile of station head 2 metre temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'station_head_temperature_2m_p90',
        description: |||
          90th percentile of station head 2 metre temperature
        |||,
        'gee:units': units.kelvin
      }
    ],
    'gee:visualizations': [
      {
        display_name: 'Station Head Temperature 2m Mean',
        lookat: {
          lat: 52.48,
          lon: 71.72,
          zoom: 1,
        },
        image_visualization: {
          band_vis: {
            min: [
              220
            ],
            max: [
              350,
            ],
            palette: ['darkblue', 'blue', 'cyan', 'green', 'yellow', 'orange', 'red', 'darkred'],
            bands: [
              'station_head_temperature_2m_mean',
            ],
          },
        },
      },
    ],
  },
  'sci:citation': |||
    For Real-Time Experimental Data, please see the applicable Terms of Use
    for citation requirements.

    If you disclose findings arising from the Historical Data, you must cite
    "&copy; 2026 DeepMind Technologies Limited's machine learning models used to
    create the experimental data made available at
    [https://developers.google.com/earth-engine/datasets/catalog/projects_gcp-public-data-weathernext_assets_weathernext_3_0_0_0p05deg](https://developers.google.com/earth-engine/datasets/catalog/projects_gcp-public-data-weathernext_assets_weathernext_3_0_0_0p05deg)
    under CC BY 4.0 licence terms. This data is intended for experimental
    modelling only and is not intended, validated, or approved for real
    world use."
  |||,
  'gee:unusual_terms_of_use': true,
  'gee:terms_of_use': |||
    The Historic Experimental Data is licensed under the Creative Commons
    Attribution International License, Version 4.0 (CC BY 4.0).

    The Real-Time Experimental Data is made available under the following
    GDM Real-Time Weather Forecasting Experimental Data [Terms of Use](https://storage.googleapis.com/weathernext-public/terms-of-use.pdf).

    **Third-party materials**

    Use of the third-party materials referred to in the Acknowledgements
    section may be governed by separate terms and conditions or license
    provisions. Your use of the third-party materials is subject to any such
    terms and you should check that you can comply with any applicable
    restrictions or terms and conditions before use.
  |||,
}
