local id = 'projects/gcp-public-data-weathernext/assets/weathernext_3_0_0_0p1deg';
local subdir = 'gcp-public-data-weathernext';

local ee_const = import 'earthengine_const.libsonnet';
local ee = import 'earthengine.libsonnet';
local spdx = import 'spdx.libsonnet';
local units = import 'units.libsonnet';

local basename = std.strReplace(id, '/', '_');
local base_filename = basename + '.json';
local self_ee_catalog_url = ee_const.ee_catalog_url + basename;
local catalog_subdir_url = ee_const.catalog_base + subdir + '/';
local parent_url = catalog_subdir_url + 'catalog.json';
local self_url = catalog_subdir_url + base_filename;

local license = spdx.proprietary;

{
  'gee:user_uploaded': true,
  stac_version: ee_const.stac_version,
  type: ee_const.stac_type.collection,
  stac_extensions: [
    ee_const.ext_eo,
    ee_const.ext_sci,
  ],
  id: id,
  title: 'WeatherNext 3 (0.1&deg;)',
  'gee:type': ee_const.gee_type.image_collection,
  description: |||
    WeatherNext 3 (0.1&deg;) dataset is an experimental dataset of global
    medium-range **ensemble weather forecasts** by Google DeepMind and Google
    Research, produced by an operational version of the model described in:
    [WeatherNext 3: Increasing resolution and performance of global weather
    models with raw observations](https://storage.googleapis.com/deepmind-media/papers/weathernext_3.pdf).

    **Data Access**

    To request access to the experimental dataset, please submit the
    [WeatherNext Data Request form](https://docs.google.com/forms/d/e/1FAIpQLSeCf1JY8G78UDWzbm0ly9kJxfSjUIJT5WyMR_HiNqCm-IHIBg/viewform).

    **Model Highlights**

    *   **High resolution & rapid refresh**: 0.1&deg; (~11 km) global spatial
        resolution, native 1-hour forecast timesteps, hourly initialization,
        and lead times extending up to 15 days.
    *   **Real-time observational grounding**: Integrates global geostationary
        satellite mosaics directly into model inputs, enabling rapid assimilation of
        current weather patterns.
    *   **Calibrated surface variables**: Calibrated against ground weather
        station networks for surface temperature/dewpoint and satellite
        observations (IMERG) for precipitation.
    *   **Solar & energy-focused fields**: Predicts multi-layer cloud cover and
        downward, direct, and clear-sky solar irradiance to support renewable energy
        and environmental modeling.

    This Earth Engine collection provides ensemble summary statistics (mean and spread)
    derived from the operational WeatherNext 3 ensemble, optimized for geospatial analysis.
    It includes 19 0.1&deg; gridded surface variables across six precomputed
    statistical metrics -- specifically mean, p10, p25, p50, p75, and p90 (total of 114 bands).

    Forecast Horizon:

    *   **6-hour inits (00, 06, 12, 18 UTC)**: with a 360-hour (15-day) horizon.
    *   **Interim 1-hour inits (01-05, 07-11, 13-17, 19-23 UTC)**: with a 48-hour horizon.

    Learn more about WeatherNext [here](https://developers.google.com/weathernext/guides/models).
    For access to the full ensemble dataset and atmospheric data, go to our
    [Google Cloud Storage bucket](https://developers.google.com/weathernext/guides/gcs).

    **Data Availability**

    The experimental dataset includes both real-time and historic data:

    *   **Real-Time Experimental Data**: Any data relating to a time more recent than 1 hour ago.
    *   **Historic Experimental Data**: Any data relating to a time 1 hour ago or older.

    **More information**

    *   **Model guide and specifications**: For more details on WeatherNext,
        including technical details and specifications, visit the
        [WeatherNext Models Guide](https://developers.google.com/weathernext/guides/models)
        and the [WeatherNext Developer Guide](https://developers.google.com/weathernext).
    *   **Research paper**: More information on the underlying research model is
        available [here](https://storage.googleapis.com/deepmind-media/papers/weathernext_3.pdf). Please note that
        the accuracy of this operational model may not directly correspond to the
        accuracy reported for the research model, and that additional variables
        may be included in this forecast dataset.
    *   **Contact**: For questions or usage outside permitted terms,
        contact weathernext@google.com. Any information collected via email will
        be used in accordance with [Google's Privacy Policy](https://policies.google.com/privacy).

    **Dissemination Schedule**

    For forecast release timing, expected delivery windows, and latency across platforms,
    see the [WeatherNext Dissemination Schedule](https://developers.google.com/weathernext/guides/dissemination).

    **Acknowledgements**

    This experimental dataset was generated by a model using data and products of
    the European Centre for Medium-Range Weather Forecasts (ECMWF), as well as
    additional third-party providers.  For a full list of attribution and acknowledgements,
    please see our [acknowledgements page](https://storage.googleapis.com/weathernext-public/weathernext-3-attributions-acknowledgements.pdf).
  |||,
  license: license.id,
  links: ee.standardLinks(subdir, id),
  'gee:categories': ['climate'],
  keywords: [
    'weather',
    'weathernext',
    'forecast',
    'temperature',
    'precipitation',
    'wind',
    'humidity',
    'flood',
  ],
  providers: [
    ee.producer_provider('Google', 'https://developers.google.com/weathernext'),
    ee.host_provider(self_ee_catalog_url),
  ],
  extent: ee.extent_global('2026-01-01T00:00:00Z', null),
  summaries: {
    gsd: [11132],
    'gee:schema': [
      {
        name: 'start_time',
        description: |||
          The initialization time of the forecast. This is the same for all
          forecast hours within a single model run.
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'end_time',
        description: |||
          The valid time for this specific forecast. Calculated as
          start_time + forecast_hour.
        |||,
        type: ee_const.var_type.string,
      },
      {
        name: 'forecast_hour',
        description: |||
          The forecast lead time in hours. Represents the number of hours from
          the start_time (1 to 360 for 6-hourly inits, 1 to 48 for interim
          hourly inits).
        |||,
        type: ee_const.var_type.int,
      },
      {
        name: 'ingestion_time_utc',
        description: |||
          The time when this forecast data became available in Earth Engine.
        |||,
        type: ee_const.var_type.double,
      },
      {
        name: 'B_',
        description: |||
          The band names in the order, starting from B0 to B113.
        |||,
        type: ee_const.var_type.string,
      },
    ],
    'eo:bands': [
      {
        name: 'dewpoint_temperature_2m_mean',
        description: |||
          Mean of 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'dewpoint_temperature_2m_p10',
        description: |||
          10th percentile of 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'dewpoint_temperature_2m_p25',
        description: |||
          25th percentile of 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'dewpoint_temperature_2m_p50',
        description: |||
          Median of 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'dewpoint_temperature_2m_p75',
        description: |||
          75th percentile of 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'dewpoint_temperature_2m_p90',
        description: |||
          90th percentile of 2 metre dewpoint temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'experimental_tp_1hr_mean',
        description: |||
          Mean of experimental total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'experimental_tp_1hr_p10',
        description: |||
          10th percentile of experimental total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'experimental_tp_1hr_p25',
        description: |||
          25th percentile of experimental total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'experimental_tp_1hr_p50',
        description: |||
          Median of experimental total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'experimental_tp_1hr_p75',
        description: |||
          75th percentile of experimental total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'experimental_tp_1hr_p90',
        description: |||
          90th percentile of experimental total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'high_cloud_cover_mean',
        description: |||
          Mean of high cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'high_cloud_cover_p10',
        description: |||
          10th percentile of high cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'high_cloud_cover_p25',
        description: |||
          25th percentile of high cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'high_cloud_cover_p50',
        description: |||
          Median of high cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'high_cloud_cover_p75',
        description: |||
          75th percentile of high cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'high_cloud_cover_p90',
        description: |||
          90th percentile of high cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'imerg_tp_1hr_mean',
        description: |||
          Mean of IMERG total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'imerg_tp_1hr_p10',
        description: |||
          10th percentile of IMERG total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'imerg_tp_1hr_p25',
        description: |||
          25th percentile of IMERG total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'imerg_tp_1hr_p50',
        description: |||
          Median of IMERG total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'imerg_tp_1hr_p75',
        description: |||
          75th percentile of IMERG total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'imerg_tp_1hr_p90',
        description: |||
          90th percentile of IMERG total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'low_cloud_cover_mean',
        description: |||
          Mean of low cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'low_cloud_cover_p10',
        description: |||
          10th percentile of low cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'low_cloud_cover_p25',
        description: |||
          25th percentile of low cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'low_cloud_cover_p50',
        description: |||
          Median of low cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'low_cloud_cover_p75',
        description: |||
          75th percentile of low cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'low_cloud_cover_p90',
        description: |||
          90th percentile of low cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'mean_sea_level_pressure_mean',
        description: |||
          Mean of Mean sea level pressure
        |||,
        'gee:units': units.pascal
      },
      {
        name: 'mean_sea_level_pressure_p10',
        description: |||
          10th percentile of Mean sea level pressure
        |||,
        'gee:units': units.pascal
      },
      {
        name: 'mean_sea_level_pressure_p25',
        description: |||
          25th percentile of Mean sea level pressure
        |||,
        'gee:units': units.pascal
      },
      {
        name: 'mean_sea_level_pressure_p50',
        description: |||
          Median of Mean sea level pressure
        |||,
        'gee:units': units.pascal
      },
      {
        name: 'mean_sea_level_pressure_p75',
        description: |||
          75th percentile of Mean sea level pressure
        |||,
        'gee:units': units.pascal
      },
      {
        name: 'mean_sea_level_pressure_p90',
        description: |||
          90th percentile of Mean sea level pressure
        |||,
        'gee:units': units.pascal
      },
      {
        name: 'medium_cloud_cover_mean',
        description: |||
          Mean of medium cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'medium_cloud_cover_p10',
        description: |||
          10th percentile of medium cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'medium_cloud_cover_p25',
        description: |||
          25th percentile of medium cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'medium_cloud_cover_p50',
        description: |||
          Median of medium cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'medium_cloud_cover_p75',
        description: |||
          75th percentile of medium cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'medium_cloud_cover_p90',
        description: |||
          90th percentile of medium cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'sea_surface_temperature_mean',
        description: |||
          Mean of Sea surface temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'sea_surface_temperature_p10',
        description: |||
          10th percentile of Sea surface temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'sea_surface_temperature_p25',
        description: |||
          25th percentile of Sea surface temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'sea_surface_temperature_p50',
        description: |||
          Median of Sea surface temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'sea_surface_temperature_p75',
        description: |||
          75th percentile of Sea surface temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'sea_surface_temperature_p90',
        description: |||
          90th percentile of Sea surface temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'surface_solar_radiation_downwards_1hr_mean',
        description: |||
          Mean of surface solar radiation downwards (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'surface_solar_radiation_downwards_1hr_p10',
        description: |||
          10th percentile of surface solar radiation downwards (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'surface_solar_radiation_downwards_1hr_p25',
        description: |||
          25th percentile of surface solar radiation downwards (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'surface_solar_radiation_downwards_1hr_p50',
        description: |||
          Median of surface solar radiation downwards (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'surface_solar_radiation_downwards_1hr_p75',
        description: |||
          75th percentile of surface solar radiation downwards (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'surface_solar_radiation_downwards_1hr_p90',
        description: |||
          90th percentile of surface solar radiation downwards (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'temperature_2m_mean',
        description: |||
          Mean of 2 metre temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'temperature_2m_p10',
        description: |||
          10th percentile of 2 metre temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'temperature_2m_p25',
        description: |||
          25th percentile of 2 metre temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'temperature_2m_p50',
        description: |||
          Median of 2 metre temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'temperature_2m_p75',
        description: |||
          75th percentile of 2 metre temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'temperature_2m_p90',
        description: |||
          90th percentile of 2 metre temperature
        |||,
        'gee:units': units.kelvin
      },
      {
        name: 'total_cloud_cover_mean',
        description: |||
          Mean of total cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'total_cloud_cover_p10',
        description: |||
          10th percentile of total cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'total_cloud_cover_p25',
        description: |||
          25th percentile of total cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'total_cloud_cover_p50',
        description: |||
          Median of total cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'total_cloud_cover_p75',
        description: |||
          75th percentile of total cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'total_cloud_cover_p90',
        description: |||
          90th percentile of total cloud cover
        |||,
        'gee:units': units.unspecified_fraction
      },
      {
        name: 'total_precipitation_1hr_mean',
        description: |||
          Mean of total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'total_precipitation_1hr_p10',
        description: |||
          10th percentile of total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'total_precipitation_1hr_p25',
        description: |||
          25th percentile of total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'total_precipitation_1hr_p50',
        description: |||
          Median of total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'total_precipitation_1hr_p75',
        description: |||
          75th percentile of total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'total_precipitation_1hr_p90',
        description: |||
          90th percentile of total precipitation (1hr)
        |||,
        'gee:units': units.meter
      },
      {
        name: 'total_sky_direct_solar_radiation_at_surface_1hr_mean',
        description: |||
          Mean of total sky direct solar radiation at surface (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'total_sky_direct_solar_radiation_at_surface_1hr_p10',
        description: |||
          10th percentile of total sky direct solar radiation at surface (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'total_sky_direct_solar_radiation_at_surface_1hr_p25',
        description: |||
          25th percentile of total sky direct solar radiation at surface (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'total_sky_direct_solar_radiation_at_surface_1hr_p50',
        description: |||
          Median of total sky direct solar radiation at surface (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'total_sky_direct_solar_radiation_at_surface_1hr_p75',
        description: |||
          75th percentile of total sky direct solar radiation at surface (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'total_sky_direct_solar_radiation_at_surface_1hr_p90',
        description: |||
          90th percentile of total sky direct solar radiation at surface (1hr)
        |||,
        'gee:units': units.joules_per_meter2
      },
      {
        name: 'u_component_of_wind_100m_mean',
        description: |||
          Mean of 100 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'u_component_of_wind_100m_p10',
        description: |||
          10th percentile of 100 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'u_component_of_wind_100m_p25',
        description: |||
          25th percentile of 100 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'u_component_of_wind_100m_p50',
        description: |||
          Median of 100 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'u_component_of_wind_100m_p75',
        description: |||
          75th percentile of 100 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'u_component_of_wind_100m_p90',
        description: |||
          90th percentile of 100 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'u_component_of_wind_10m_mean',
        description: |||
          Mean of 10 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'u_component_of_wind_10m_p10',
        description: |||
          10th percentile of 10 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'u_component_of_wind_10m_p25',
        description: |||
          25th percentile of 10 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'u_component_of_wind_10m_p50',
        description: |||
          Median of 10 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'u_component_of_wind_10m_p75',
        description: |||
          75th percentile of 10 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'u_component_of_wind_10m_p90',
        description: |||
          90th percentile of 10 metre U wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_100m_mean',
        description: |||
          Mean of 100 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_100m_p10',
        description: |||
          10th percentile of 100 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_100m_p25',
        description: |||
          25th percentile of 100 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_100m_p50',
        description: |||
          Median of 100 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_100m_p75',
        description: |||
          75th percentile of 100 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_100m_p90',
        description: |||
          90th percentile of 100 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_10m_mean',
        description: |||
          Mean of 10 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_10m_p10',
        description: |||
          10th percentile of 10 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_10m_p25',
        description: |||
          25th percentile of 10 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_10m_p50',
        description: |||
          Median of 10 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_10m_p75',
        description: |||
          75th percentile of 10 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'v_component_of_wind_10m_p90',
        description: |||
          90th percentile of 10 metre V wind component
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_100m_mean',
        description: |||
          Mean of 100 metre wind speed
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_100m_p10',
        description: |||
          10th percentile of 100 metre wind speed
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_100m_p25',
        description: |||
          25th percentile of 100 metre wind speed
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_100m_p50',
        description: |||
          Median of 100 metre wind speed
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_100m_p75',
        description: |||
          75th percentile of 100 metre wind speed
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_100m_p90',
        description: |||
          90th percentile of 100 metre wind speed
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_10m_mean',
        description: |||
          Mean of 10 metre wind speed
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_10m_p10',
        description: |||
          10th percentile of 10 metre wind speed
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_10m_p25',
        description: |||
          25th percentile of 10 metre wind speed
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_10m_p50',
        description: |||
          Median of 10 metre wind speed
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_10m_p75',
        description: |||
          75th percentile of 10 metre wind speed
        |||,
        'gee:units': units.velocity_si
      },
      {
        name: 'wind_speed_10m_p90',
        description: |||
          90th percentile of 10 metre wind speed
        |||,
        'gee:units': units.velocity_si
      }
    ],
    'gee:visualizations': [
      {
        display_name: 'Temperature 2m Mean',
        lookat: {
          lat: 52.48,
          lon: 71.72,
          zoom: 1,
        },
        image_visualization: {
          band_vis: {
            min: [
              220
            ],
            max: [
              350,
            ],
            palette: ['darkblue', 'blue', 'cyan', 'green', 'yellow', 'orange', 'red', 'darkred'],
            bands: [
              'temperature_2m_mean',
            ],
          },
        },
      },
    ],
  },
  'sci:citation': |||
    For Real-Time Experimental Data, please see the applicable Terms of Use
    for citation requirements.

    If you disclose findings arising from the Historical Data, you must cite
    "&copy; 2026 DeepMind Technologies Limited's machine learning models used to
    create the experimental data made available at
    [https://developers.google.com/earth-engine/datasets/catalog/projects_gcp-public-data-weathernext_assets_weathernext_3_0_0_0p1deg](https://developers.google.com/earth-engine/datasets/catalog/projects_gcp-public-data-weathernext_assets_weathernext_3_0_0_0p1deg)
    under CC BY 4.0 licence terms. This data is intended for experimental
    modelling only and is not intended, validated, or approved for real
    world use."
  |||,
  'gee:unusual_terms_of_use': true,
  'gee:terms_of_use': |||
    The Historic Experimental Data is licensed under the Creative Commons
    Attribution International License, Version 4.0 (CC BY 4.0).

    The Real-Time Experimental Data is made available under the following
    GDM Real-Time Weather Forecasting Experimental Data [Terms of Use](https://storage.googleapis.com/weathernext-public/terms-of-use.pdf).

    **Third-party materials**

    Use of the third-party materials referred to in the Acknowledgements
    section may be governed by separate terms and conditions or license
    provisions. Your use of the third-party materials is subject to any such
    terms and you should check that you can comply with any applicable
    restrictions or terms and conditions before use.
  |||,
}
