local subdir = 'NASA';

local ee_const = import 'earthengine_const.libsonnet';
local ee = import 'earthengine.libsonnet';
local spdx = import 'spdx.libsonnet';
local units = import 'units.libsonnet';

local license = spdx.proprietary;

local self_ee_catalog_url(id) =
  ee_const.ee_catalog_url + std.strReplace(id, '/', '_');

{
  nasa_nisar_sme2_collection(cfg) ::
    local version_config = if std.objectHas(cfg, 'version_config') then cfg.version_config else null;
    local version = if version_config != null then version_config.version else cfg.version;
    local doi = cfg.doi;
    local provider_id = cfg.provider_id;
    local status = if std.objectHas(cfg, 'status') then cfg.status else null;
    local start_date = cfg.start_date;
    local end_date = if std.objectHas(cfg, 'end_date') then cfg.end_date else null;
    {
      stac_version: ee_const.stac_version,
      type: ee_const.stac_type.collection,
      stac_extensions: [
        ee_const.ext_eo,
        ee_const.ext_sci,
        ee_const.ext_ver,
      ],
      id: cfg.id,
      title: 'NISAR L3 Soil Moisture (SME2) 200m ' + version +
        (if status == 'deprecated' then ' [deprecated]' else ''),
      version: version,
      [if status != null then 'gee:status']: status,
      'gee:type': ee_const.gee_type.image_collection,
      description: |||
        The NASA-ISRO Synthetic Aperture Radar (NISAR) Level 3 Soil Moisture
        (SME2) dataset provides estimated volumetric soil moisture (0–5 cm depth)
        at 200 m spatial resolution on the global cylindrical equal-area
        EASE-Grid 2.0 (EPSG:6933).

        NISAR is a joint Earth-observing mission developed by NASA and the Indian
        Space Research Organisation (ISRO). The SME2 product is generated by the
        Science Data System (SDS) at NASA JPL and distributed by the Alaska
        Satellite Facility (ASF) DAAC. Soil moisture estimates are derived from
        NISAR L2 geocoded polarimetric covariance (GCOV) radar backscatter
        measurements acquired in L-band (Frequency A: 1.239 GHz, Frequency B:
        1.2935 GHz) combined with ancillary data (such as land cover, surface
        temperature, and waterbody fraction).

        In addition to soil moisture estimates and retrieval uncertainty, each
        granule contains pixel-level quality flags, ancillary land cover and water
        fraction, local incidence angle, and dynamic calibrated linear radar
        backscatter coefficients (`sigma0`) for available polarization channels
        across Frequency A and B. The availability of individual `sigma0` bands
        varies by the polarizations acquired for each granule. The available
        polarizations for each granule are provided in the
        `transmitterReceiverPolarizationA`
        and `transmitterReceiverPolarizationB` metadata properties.

        ### Composite Release ID (`crid`) & Versioning

        NISAR granules follow a standard product naming convention that includes
        the **Composite Release ID (`crid`)** property (part 13 of the granule
        identifier), which defines the algorithm and calibration software release:

        * **Beta Release (`X...`)**: Granules with `crid` starting with `X`
          (e.g., `X05010`) were generated during the preliminary evaluation phase
          (October 2025 to January 2026) in the [NASA/NISAR/L3_SME2_BETA_V1](NASA_NISAR_L3_SME2_BETA_V1)
          collection.
        * **Provisional Release (`P...`)**: Granules with `crid` starting with `P`
          (e.g., `P05023`) feature refined calibration and updated PGE software
          in the [NASA/NISAR/L3_SME2_PROVISIONAL_V1](NASA_NISAR_L3_SME2_PROVISIONAL_V1)
          collection.
        * **Future Validated Releases (`R...`)**: As algorithm validation matures,
          operational and science-grade releases will be identified by their
          corresponding operational `crid` values.

        In Earth Engine, each image retains `crid` as a first-class metadata property.
        Users can filter and inspect images by `crid` (e.g., `image.get('crid')` or
        `ee.Filter.stringStartsWith('crid', 'P')`) to track specific PGE releases
        and calibration tiers.

        ### Documentation

        * [NISAR SME2 Product Documentation](https://nisar-docs.asf.alaska.edu/sme2/)
        * [NISAR Naming Conventions Guide](https://nisar-docs.asf.alaska.edu/naming-conventions/)
        * [NASA Earthdata Dataset Landing Page](https://doi.org/%s)
      ||| % doi,
      license: license.id,
      links: ee.standardLinks(subdir, cfg.id) + [
        {
          rel: ee_const.rel.cite_as,
          href: 'https://doi.org/' + doi,
        },
      ] + (if version_config != null then version_config.version_links else []),
      'gee:categories': ['soil'],
      keywords: [
        'backscatter',
        'nasa',
        'radar',
        'sar',
        'soil_moisture',
        'surface',
      ],
      providers: [
        ee.producer_provider('NASA JPL / ASF DAAC', 'https://doi.org/' + doi),
        ee.host_provider(self_ee_catalog_url(cfg.id)),
      ],
      'gee:provider_ids': [
        provider_id,
      ],
      extent: ee.extent_global(start_date, end_date),
      summaries: {
        gsd: [
          200.18,
        ],
        platform: [
          'NISAR',
        ],
        instruments: [
          'L-SAR',
        ],
        'eo:bands': [
          {
            name: 'soilMoisture',
            description: 'Estimated volumetric soil moisture (0–5 cm depth)',
            'gee:units': units.volume_fraction,
          },
          {
            name: 'uncertainty',
            description: 'Soil moisture retrieval uncertainty standard deviation',
            'gee:units': units.volume_fraction,
          },
          {
            name: 'qualityFlag',
            description: 'Pixel-level retrieval quality flag',
            'gee:units': units.dimensionless,
          },
          {
            name: 'landCover',
            description: 'Ancillary land cover classification code',
            'gee:units': units.dimensionless,
          },
          {
            name: 'waterFraction',
            description: 'Fraction of the grid cell covered by water',
            'gee:units': units.area_fraction,
          },
          {
            name: 'incidenceAngle',
            description: 'Local radar incidence angle',
            'gee:units': units.degree,
          },
          {
            name: 'sigma0HH_A',
            description:
              'Calibrated radar backscatter (sigma0) for HH polarization at Frequency A (1.239 GHz). ' +
              'Availability varies by the available polarizations for each granule.',
            'gee:units': units.dimensionless,
          },
          {
            name: 'sigma0HV_A',
            description:
              'Calibrated radar backscatter (sigma0) for HV polarization at Frequency A (1.239 GHz). ' +
              'Availability varies by the available polarizations for each granule.',
            'gee:units': units.dimensionless,
          },
          {
            name: 'sigma0VV_A',
            description:
              'Calibrated radar backscatter (sigma0) for VV polarization at Frequency A (1.239 GHz). ' +
              'Availability varies by the available polarizations for each granule.',
            'gee:units': units.dimensionless,
          },
          {
            name: 'sigma0VH_A',
            description:
              'Calibrated radar backscatter (sigma0) for VH polarization at Frequency A (1.239 GHz). ' +
              'Availability varies by the available polarizations for each granule.',
            'gee:units': units.dimensionless,
          },
          {
            name: 'sigma0HH_B',
            description:
              'Calibrated radar backscatter (sigma0) for HH polarization at Frequency B (1.2935 GHz). ' +
              'Availability varies by the available polarizations for each granule.',
            'gee:units': units.dimensionless,
          },
          {
            name: 'sigma0HV_B',
            description:
              'Calibrated radar backscatter (sigma0) for HV polarization at Frequency B (1.2935 GHz). ' +
              'Availability varies by the available polarizations for each granule.',
            'gee:units': units.dimensionless,
          },
          {
            name: 'sigma0VV_B',
            description:
              'Calibrated radar backscatter (sigma0) for VV polarization at Frequency B (1.2935 GHz). ' +
              'Availability varies by the available polarizations for each granule.',
            'gee:units': units.dimensionless,
          },
          {
            name: 'sigma0VH_B',
            description:
              'Calibrated radar backscatter (sigma0) for VH polarization at Frequency B (1.2935 GHz). ' +
              'Availability varies by the available polarizations for each granule.',
            'gee:units': units.dimensionless,
          },
        ],
        'gee:schema': [
          {
            name: 'cycleNumber',
            description: 'NISAR orbit cycle number',
            type: ee_const.var_type.int,
          },
          {
            name: 'relativeOrbitTrack',
            description: 'Relative orbit track number',
            type: ee_const.var_type.int,
          },
          {
            name: 'passDirection',
            description: "Pass direction: 'A' for Ascending, 'D' for Descending",
            type: ee_const.var_type.string,
          },
          {
            name: 'frameNumber',
            description: 'Frame number along track',
            type: ee_const.var_type.int,
          },
          {
            name: 'swathMode',
            description: 'Swath bandwidth mode (e.g., 4005, 2005, 0505, 0005)',
            type: ee_const.var_type.string,
          },
          {
            name: 'polarizationMode',
            description: 'Polarization mode code across Frequency A and B (e.g., DHDH, SVSH, NASV, QPDH)',
            type: ee_const.var_type.string,
          },
          {
            name: 'frequencyBand',
            description: "Transmitted frequency band ('A' or 'B')",
            type: ee_const.var_type.string,
          },
          {
            name: 'crid',
            description: "Composite Release ID identifying the processing software release and calibration tier (e.g., 'X...' for Beta, 'P...' for Provisional, 'R...' for Validated)",
            type: ee_const.var_type.string,
          },
          {
            name: 'status',
            description: "Granule status ('N' for Nominal)",
            type: ee_const.var_type.string,
          },
          {
            name: 'productClass',
            description: "Product class ('P' for Standard, 'F' for Fast/Urgent Response)",
            type: ee_const.var_type.string,
          },
          {
            name: 'processingCenter',
            description: "Processing facility ('J' for JPL, 'I' for ISRO)",
            type: ee_const.var_type.string,
          },
          {
            name: 'counter',
            description: 'Processing run counter',
            type: ee_const.var_type.int,
          },
          {
            name: 'transmitterReceiverPolarizationA',
            description: 'List of polarizations available for Frequency A',
            type: ee_const.var_type.string_list,
          },
          {
            name: 'transmitterReceiverPolarizationB',
            description: 'List of polarizations available for Frequency B',
            type: ee_const.var_type.string_list,
          },
        ],
        'gee:visualizations': [
          {
            display_name: 'Soil Moisture',
            lookat: {
              lat: 35.0,
              lon: 140.0,
              zoom: 6,
            },
            image_visualization: {
              band_vis: {
                min: [0.0],
                max: [0.5],
                bands: ['soilMoisture'],
                palette: [
                  '0300ff',
                  '418504',
                  'efff07',
                  'efff07',
                  'ff0303',
                ],
              },
            },
          },
        ],
      },
      'sci:citation': |||
        NASA/JPL/ASF. (2025). NISAR %s Soil Moisture (Version 1) [Data set].
        NASA Alaska Satellite Facility (ASF) DAAC.
        Retrieved from https://doi.org/%s
      ||| % [if status == 'deprecated' || std.startsWith(version, 'Beta') then 'Beta' else 'Provisional', doi],
      'gee:terms_of_use': |||
        This dataset is in the public domain and is available
        without restriction on use and distribution. See [NASA's
        Earth Science Data & Information Policy](https://www.earthdata.nasa.gov/engage/open-data-services-and-software/data-and-information-policy)
        for additional information.
      |||,
    },
}
