local id = 'LANDSAT';
local ee_const = import 'earthengine_const.libsonnet';
local ee = import 'earthengine.libsonnet';

local basename = 'catalog';
local base_filename = basename + '.json';
local base_url = ee_const.catalog_base + 'LANDSAT/';
local parent_url = ee_const.catalog_base + 'catalog.json';
local self_url = base_url + base_filename;

{
  stac_version: ee_const.stac_version,
  type: ee_const.stac_type.catalog,
  id: id,
  title: id,
  description: importstr 'description.md',
  links: [
    ee.link.root(),
    ee.link.parent(parent_url),
    ee.link.self_link(self_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_32DAY_BAI', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_32DAY_EVI', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_32DAY_NBR', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_32DAY_NDVI', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_32DAY_NDWI', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_8DAY_BAI', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_8DAY_EVI', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_8DAY_NBR', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_8DAY_NDVI', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_8DAY_NDWI', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_ANNUAL_BAI', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_ANNUAL_EVI', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_ANNUAL_NBR', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_ANNUAL_NDVI', base_url),
    ee.link.child_collection('LANDSAT_COMPOSITES_C02_T1_L2_ANNUAL_NDWI', base_url),
    ee.link.child_collection('LANDSAT_GLS1975', base_url),
    ee.link.child_collection('LANDSAT_GLS1975_MOSAIC', base_url),
    ee.link.child_collection('LANDSAT_GLS2005', base_url),
    ee.link.child_collection('LANDSAT_GLS2005_L5', base_url),
    ee.link.child_collection('LANDSAT_GLS2005_L7', base_url),
    ee.link.child_collection('LANDSAT_LC08_C02_T1', base_url),
    ee.link.child_collection('LANDSAT_LC08_C02_T1_L2', base_url),
    ee.link.child_collection('LANDSAT_LC08_C02_T1_RT', base_url),
    ee.link.child_collection('LANDSAT_LC08_C02_T1_RT_TOA', base_url),
    ee.link.child_collection('LANDSAT_LC08_C02_T1_TOA', base_url),
    ee.link.child_collection('LANDSAT_LC08_C02_T2', base_url),
    ee.link.child_collection('LANDSAT_LC08_C02_T2_L2', base_url),
    ee.link.child_collection('LANDSAT_LC08_C02_T2_TOA', base_url),
    ee.link.child_collection('LANDSAT_LC09_C02_T1', base_url),
    ee.link.child_collection('LANDSAT_LC09_C02_T1_L2', base_url),
    ee.link.child_collection('LANDSAT_LC09_C02_T1_TOA', base_url),
    ee.link.child_collection('LANDSAT_LC09_C02_T2', base_url),
    ee.link.child_collection('LANDSAT_LC09_C02_T2_L2', base_url),
    ee.link.child_collection('LANDSAT_LC09_C02_T2_TOA', base_url),
    ee.link.child_collection('LANDSAT_LE07_C02_T1', base_url),
    ee.link.child_collection('LANDSAT_LE07_C02_T1_L2', base_url),
    ee.link.child_collection('LANDSAT_LE07_C02_T1_RT', base_url),
    ee.link.child_collection('LANDSAT_LE07_C02_T1_RT_TOA', base_url),
    ee.link.child_collection('LANDSAT_LE07_C02_T1_TOA', base_url),
    ee.link.child_collection('LANDSAT_LE07_C02_T2', base_url),
    ee.link.child_collection('LANDSAT_LE07_C02_T2_L2', base_url),
    ee.link.child_collection('LANDSAT_LE07_C02_T2_TOA', base_url),
    ee.link.child_collection('LANDSAT_LM01_C02_T1', base_url),
    ee.link.child_collection('LANDSAT_LM01_C02_T2', base_url),
    ee.link.child_collection('LANDSAT_LM02_C02_T1', base_url),
    ee.link.child_collection('LANDSAT_LM02_C02_T2', base_url),
    ee.link.child_collection('LANDSAT_LM03_C02_T1', base_url),
    ee.link.child_collection('LANDSAT_LM03_C02_T2', base_url),
    ee.link.child_collection('LANDSAT_LM04_C02_T1', base_url),
    ee.link.child_collection('LANDSAT_LM04_C02_T2', base_url),
    ee.link.child_collection('LANDSAT_LM05_C02_T1', base_url),
    ee.link.child_collection('LANDSAT_LM05_C02_T2', base_url),
    ee.link.child_collection('LANDSAT_LT04_C02_T1', base_url),
    ee.link.child_collection('LANDSAT_LT04_C02_T1_L2', base_url),
    ee.link.child_collection('LANDSAT_LT04_C02_T1_TOA', base_url),
    ee.link.child_collection('LANDSAT_LT04_C02_T2', base_url),
    ee.link.child_collection('LANDSAT_LT04_C02_T2_L2', base_url),
    ee.link.child_collection('LANDSAT_LT04_C02_T2_TOA', base_url),
    ee.link.child_collection('LANDSAT_LT05_C02_T1', base_url),
    ee.link.child_collection('LANDSAT_LT05_C02_T1_L2', base_url),
    ee.link.child_collection('LANDSAT_LT05_C02_T1_TOA', base_url),
    ee.link.child_collection('LANDSAT_LT05_C02_T2', base_url),
    ee.link.child_collection('LANDSAT_LT05_C02_T2_L2', base_url),
    ee.link.child_collection('LANDSAT_LT05_C02_T2_TOA', base_url),
    ee.link.child_collection('LANDSAT_MANGROVE_FORESTS', base_url),
  ],
}
