local id = 'COPERNICUS/MARINE/WAV/ANFC_0_083DEG_STATIC';
local subdir = 'COPERNICUS';

local ee_const = import 'earthengine_const.libsonnet';
local ee = import 'earthengine.libsonnet';
local spdx = import 'spdx.libsonnet';
local units = import 'units.libsonnet';
local marine_common = import 'templates/COPERNICUS_MARINE_OC_GLO_BGC.libsonnet';

local license = spdx.cc_by_4_0;

local basename = std.strReplace(id, '/', '_');
local base_filename = basename + '.json';

local self_ee_catalog_url = ee_const.ee_catalog_url + basename;

{
  stac_version: ee_const.stac_version,
  type: ee_const.stac_type.collection,
  stac_extensions: [
    ee_const.ext_eo,
    ee_const.ext_sci,
  ],
  id: id,
  title: 'Global Ocean Waves Static Bathymetry',
  'gee:type': ee_const.gee_type.image_collection,
  description: |||
    Static bathymetry for the Global Ocean Waves Analysis and Forecast
    system. This dataset provides the sea floor depth in meters.

    The global wave system of Meteo-France is based on the wave model
    MFWAM which is a third generation wave model. MFWAM uses the
    computing code ECWAM-IFS-38R2 with dissipation terms developed by
    Ardhuin et al. (2010). The model MFWAM was upgraded on November 2014
    thanks to improvements obtained from the European research project
    'my wave' (Janssen et al. 2014).

    The model mean bathymetry is generated by using 2-minute gridded
    global topography data ETOPO2/NOAA. Native model grid is irregular
    with decreasing distance in the latitudinal direction close to the
    poles. At the equator the distance in the latitudinal direction is
    more or less fixed with grid size 1/10 degrees. The operational
    model MFWAM is driven by 6-hourly analysis and 3-hourly forecasted
    winds from the IFS-ECMWF atmospheric system. The wave spectrum is
    discretized in 24 directions and 30 frequencies starting from 0.035
    Hz to 0.58 Hz. The model MFWAM uses the assimilation of altimeters
    with a time step of 6 hours. The global wave system provides
    analysis 4 times a day, and a forecast of 10 days at 0:00 UTC. The
    wave model MFWAM uses the partitioning to split the swell spectrum in
    primary and secondary swells.

    GLOBAL_ANALYSISFORECAST_WAV_001_027, implemented by Mercator Ocean
    International. It provides a comprehensive overview of the global
    ocean wave analysis and forecasting system produced by Meteo-France.
    The system delivers aggregated analyses and a 10-day forecast,
    updated twice-daily, including various integrated wave parameters
    such as significant wave height, period, direction, and Stokes drift
    for both the total wave spectrum and partitioned waves (wind wave,
    primary and secondary swell).

  |||,
  license: license.id,
  links: ee.standardLinks(subdir, id),
  'gee:categories': ['oceans'],
  keywords: [
    'copernicus',
    'marine',
    'bathymetry',
  ],
  providers: [
    ee.producer_provider('Copernicus Marine Service Global Ocean Waves and Forecasts', 'https://data.marine.copernicus.eu/product/GLOBAL_ANALYSISFORECAST_WAV_001_027/description'),
    ee.host_provider(self_ee_catalog_url),
  ],
  extent: ee.extent_global('2022-06-01T00:00:00Z', null),
  summaries: {
    gsd: [
      9276.62,
    ],
    'eo:bands': [
      {
        name: 'deptho',
        description: 'Sea floor depth',
        'gee:units': units.meter,
      },
    ],
    'gee:visualizations': [
      {
        display_name: 'Sea Floor Depth',
        lookat: {
          lat: 0,
          lon: 0,
          zoom: 2,
        },
        image_visualization: {
          band_vis: {
            min: [-8000],
            max: [0],
            palette: ['000080', '0000d0', '0000ff', '87ceeb', 'ffffff'],
            bands: ['deptho'],
          },
        },
      },
    ],
  },
  'sci:citation': |||
    E.U. Copernicus Marine Service Information (2024). Global Ocean Waves Analysis and Forecast.
    [doi.org/10.48670/moi-00017](https://doi.org/10.48670/moi-00017)
  |||,
  'gee:terms_of_use': marine_common.term_of_use,
}