"""Units used throughout the Earth Engine catalog.

Mirrors the units listed here:

https://github.com/google/earthengine-catalog/blob/main/catalog/units.libsonnet
"""

# TODO(schwehr): Load this from units.libsonnet
UNITS = frozenset({
    '%',
    'Area fraction',
    'Dimensionless',
    'Mass fraction',
    'Mol fraction',
    'Fraction',
    'Volume fraction',
    'Dobson',
    'GHz',
    'Gg',
    'J/kg',
    'J/m^2',
    'K',
    'nmi',
    'MW',
    'Mg/ha',
    'N/m^2',
    'Pa',
    'W/m^2',
    'y',
    'cm',
    'count',
    'count/d',
    'd',
    'dB',
    'deg',
    'dn',
    'h',
    'h/km^2',
    'ha',
    'hPa',
    'kg/m^2',
    'kg/m^2/s',
    'kg/m^3',
    'kPa',
    'km',
    'km^2',
    'kt',
    'm',
    'm/s',
    'm/s^2',
    'm^2',
    'mbar',
    'mg/m^3',
    'min',
    'mm',
    'mm/d',
    'nanoWatts/sr/cm^2',
    'pixel',
    'psu',
    'rad',
    '&deg;C',
    '&micro;m',
})
