# Find common misspellings
# https://github.com/codespell-project/codespell
# https://github.com/codespell-project/actions-codespell
name: codespell
on: [push, pull_request]
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: "ake,alos,doas,fallow,ges,ists,markey,metdata,nd,ned,ot,pervious,pres,regio,ro,ser,vas,watermask,wich"

